### ISSUE TITLE
Usernames with underscores and spaces are broken in Access Control List Administration frame

### ISSUE THREAD

**Issue by AfiMorgan** [LibreHealthIO/lh-ehr#1093]
## Clicking on "edit" on a user with an underscore in the name returns a 404 - error.

Cause:  
the function **generic_click()** in _/interface/usergroup/adminacl.php_ splits the ID of the <a> into an array using underscores.
For the user "admin" the **ID** of the <a> tag is "admin_membership_list" which gets split into:
temparray[0] = admin,
temparray[1] = membership,
temparray[2] = list

If a user has an underscore in their name (e.g. super_admin), the array will contain an extra element:
temparray[0] = super,
temparray[1] = admin.
temparray[2] = membership,
temparray[3] = list

This causes an offset and invalid values for the control and action.

**Comment by teryhill** [comment]
@naveen17797 If you would like . If I remember correctly it just needs to allow it.

**Comment by AfiMorgan** [comment]
@teryhill no problem

@naveen17797 I was able to work around the underscore issue with this quick fix right after the declaration `temparray = cthis.id.split("_");`
```
if(temparray.length > 3){
    var temparrayLengthFixed = temparray.length - 3;
    var taOriginalName = "";
    for(var taCount = 0; taCount <= temparrayLengthFixed; taCount++){
        if(taCount > 0){
            taOriginalName += "_" + temparray[taCount];
        }else{
            taOriginalName += temparray[taCount];
        }
    }
    temparray.splice(0, temparrayLengthFixed + 1);
    temparray.splice(0,0,taOriginalName);
}
```

**Comment by naveen17797** [comment]
you can sent the PR if you have fixed it @AfiMorgan

**Comment by AfiMorgan** [comment]
@naveen17797 I'll send a PR once I get the other issue with the space in the username fixed :)

**Comment by teryhill** [comment]
@naveen17797  about line 106 in adminacl.php , then add the supplied code. Could add .replace(" ","\\ ") to the end of lines 313,314 and 316

**Comment by teryhill** [comment]
![image](https://user-images.githubusercontent.com/4655366/38319126-0c9bec0e-37ff-11e8-8f19-917a9c225c1d.png)

Like this

**Comment by teryhill** [comment]
closed on gitlab
