### ISSUE TITLE
REVIEW CODEz PLEEZE

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/lh-ehr#1138]
Not getting enough code reviews.  Currently, there are 23 pull requests, some of them waiting on second review, many of them are staged PR's that need merging before work can continue.  Please do some code reviews friends and neighbors.  If we each did 1 (one) a review every week, there would never be anything waiting on reviews.

**Comment by tmccormi** [comment]
I looked at them last week and none were ready, they all looked like WIP to me.  Will look again

**Comment by muarachmann** [comment]
Ok @aethelwulffe roger that
