### ISSUE TITLE
Facility list in calendar really horrible.

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/lh-ehr#1145]
The list of facilities should not be "buttonized".
It should be an orderly row of *selectable* text labels with a background color indicative of the color selected for the facility.
Current (in theme "light"):
![image](https://user-images.githubusercontent.com/553751/40499757-de621e8e-5f50-11e8-875d-f6da402cbcbd.png)

Past (how it should look:
![image](https://user-images.githubusercontent.com/553751/40499830-1dc8300e-5f51-11e8-861a-c1178b098f35.png)

The only reason for the facilities to be listed is to provide a color legend for the colorization of appointments when the user calendar color preference is set to "by facility".  Otherwise, the drop-down should handle this.
This stuff is pretty important for providers that have to hit the road a lot to visit inpatient care locations, and clinics with lots of offices.

**Comment by apooravc** [comment]
Working on it.

**Comment by aethelwulffe** [comment]
Great answer man!
