### ISSUE TITLE
User Admin Save Invisible Light Theme

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/lh-ehr#1146]
Without highlighting:
![image](https://user-images.githubusercontent.com/553751/40500314-59c17f06-5f52-11e8-9979-eab22297a6ee.png)

With Highlighting:
![image](https://user-images.githubusercontent.com/553751/40500331-6759dbae-5f52-11e8-83a9-0ea60d6d3eff.png)

**Comment by aethelwulffe** [comment]
izimodal please save us.

**Comment by apooravc** [comment]
@aethelwulffe If I'm not wrong, #1136  would take care of this. Similar issue with add/edit facilities, taken care by [iziModal-facilities](https://github.com/LibreHealthIO/lh-ehr/pull/1134).

**Comment by aethelwulffe** [comment]
I thought so.  This is a non-issue then, but since this is linked to the PR numbers now, It will be good to leave this open for testing review things to check.

thanks!  Sooo looking forward to moving to the new modal window.
