### ISSUE TITLE
Unknown directory asset 404 action

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/lh-ehr#1152]
\LibreEHR\interface\tags_filters\models\PatientTagEntry.php:

 line  16 :            ` new Column(array('width' => '70px', 'behavior' => new ActiveStatic(array('name' => 'tag_name', 'class' => 'tag_name', 'url' => $GLOBALS['webroot'] . '/interface/crisisprep/index.php?action=dispatch!element_changed')), 'title' => 'Tag Name', 'data' => 'T.tag_name')),`
 
Anyone know what the heck "crisisprep/" is/was?  This looks like code from some custom implementation.

**Comment by aethelwulffe** [comment]
A search for "crisisprep" lands me here:  https://crisisprep.mi-squared.com/openemr/interface/login/login_frame.php?site=default
-Guess we know where this came from... :shipit:

**Comment by aethelwulffe** [comment]
404 Not Found
       /LibreEHR/interface/tags_filters/javascript;: 2 Time(s)

-Any ideas?  Can't figure out what formed this bad request, where or when.  Something assembled it, 'cause there is no "tags_filters/javascript".

Maybe here(this looks like "javascript:" is an empty or local function call)?:
LibreEHR\interface\tags_filters\assets\bootstrap\css\bootstrap.css:
  210    }
  211    a[href^="#"]:after,
  212:   a[href^="javascript:"]:after {
  213      content: "";
  214    }

Or one of these (Line 9 does NOT look like a function call without the colon, right)?:
LibreEHR\interface\tags_filters\views\tags_demographics.php:
    8                          <a id="tags-edit-button" onclick="top.restoreSession()"
    9:                            href="javascript;"

**Comment by teryhill** [comment]
@kchapple Can you help us out here?

**Comment by kchapple** [comment]
I used the data tables backen framework from another project. Should be /interface/tags_filters/...
