### ISSUE TITLE
Is a form active

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#1167]
Adding a means to check if a form is active. This function checks to see if the sql file (table.sql) has been run and it checks to see if the form is enabled in forms admin.

This can be used test and ensure the form is active in the system. Will be handy for the forms generator and the encounter revamp.

**Comment by aethelwulffe** [comment]
The active form is checked with a query to the `registry` table.  Nothing else is needed.

**Comment by teryhill** [comment]
Merged closing
