### ISSUE TITLE
Added provider name display last name first initial

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#1184]
We had full name, last name and resource. I added last name first initial 

![image](https://user-images.githubusercontent.com/4655366/41627983-79e3121a-73f0-11e8-94df-a32dc9939e1c.png)

**Comment by apooravc** [comment]
@teryhill issue could be closed now.

**Comment by teryhill** [comment]
Yes @apooravc  it can. Merged closing.
