### ISSUE TITLE
Tag's code runs always impacting performance of certain screens 

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#1229]
The tags system is not controlled via a globals switch to turn it on and off, This causes performance hits on large systems. Started with the most obvious screen demographics.

**Comment by tmccormi** [comment]
We have performance update coming for tags that we just deployed to a customer today ... just FYI

**Comment by teryhill** [comment]
Does it include the ability to turn it off, I know Ken did not think the collapsing of it on the demographics screen was needed?

**Comment by tmccormi** [comment]
It's a module.  Delete the directory and it's "off".  Option to turn it off is ok too, I guess but might not be needed in the near future if the reason is performance.

**Comment by teryhill** [comment]
If you delete the module what happens when do_action gets called

**Comment by tmccormi** [comment]
nothing, if there is no code the action just moves on.  That't the whole purpure of the do_action hooks

**Comment by tmccormi** [comment]
@teryhill I think your change and Kens have both been merged now.  Closing this.
