### ISSUE TITLE
BatchCom Tab not displaying

### ISSUE THREAD

**Issue by muarachmann** [LibreHealthIO/lh-ehr#1243]
Tab title not being shown. 
Click on **Miscellaneous > BatchCom**

![kazam_screenshot_00041](https://user-images.githubusercontent.com/16350814/45723384-07bf0500-bb7f-11e8-882d-af08897786b1.png)

**Comment by aethelwulffe** [comment]
That is perhaps because your theme is set to "Light"?
Light does not work, yet it is our default on install.  Dump light theme, and we might be fine.  Light has issues in appointments and a number of other places where there are tab labels.

**Comment by muarachmann** [comment]
Nope on install/re-install i always choose prism. I found a way to fix it. But i have messed up my branch trying to do some rebase i have alot of PRs pending
