### ISSUE TITLE
System allows creation of multiple encounters on a DOS 

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#1265]
Currently the system allows creation of multiple encounters on a DOS when auto creating an encounter. If you set the status of an appointment to arrived and have the auto generate encounters checked in globals the encounter will be created, however if you change the status to something else and save then go back in and change the status to arrived it will create another encounter.

**Comment by tmccormi** [comment]
Is the fix just for that problem?  IE: Auto encounters, because creating more than one encounter per visit (manually) is normal for many practices

**Comment by teryhill** [comment]
Yes just for auto encounters. They should only create i encounter per appointment automatically.

**Comment by tmccormi** [comment]
merged
