### ISSUE TITLE
Missing git submodule is throwing the repository into a weird state 

### ISSUE THREAD

**Issue by robbyoconnor** [LibreHealthIO/lh-ehr#1274]
I found the culprit [here](https://github.com/LibreHealthIO/lh-ehr/tree/master/interface/tags_filters/vendor/twitter).

**Comment by robbyoconnor** [comment]
@tmccormi looks like you were the one who merged this in.

**Comment by tmccormi** [comment]
There should not be any .gitmodules in our repo.
That folder had no content...  So I have no ideal what you are talking about.

/opt/gitrepos/lh-ehr/interface/tags_filters/vendor/twitter/bootstrap (master)$ ls -la
total 8
drwxrwxr-x 2 tony tony 4096 Jun 13 22:18 .
drwxrwxr-x 3 tony tony 4096 Jun 13 22:18 ..

How do you reproduce this error, I'm not seeing it in anything I do.

**Comment by tmccormi** [comment]
I have no idea what 'projectile' is or how and why it's being used.   It's not part of LibreEHR.  Is it part of the CI/CD you are trying to setup or something?

**Comment by robbyoconnor** [comment]
It's an emacs project-management minor-mode :)

**Comment by robbyoconnor** [comment]
It's not related to LibreEHR but it _DID_ turn up a missing submodule -- we need to either add the submodule or nuke the folder, I chose to nuke the folder as I didn't know which version to add.

**Comment by tmccormi** [comment]
@kchapple Since Tags is your baby, can you weigh in here?  Is it OK to remove this asset?

**Comment by robbyoconnor** [comment]
@tmccormi the issue is that it's not there -- what we _COULD_ do is add the proper commit as a submodule and fix it that way...but the asset doesn't actually exist...look at the link on github -- you'll see it points nowhere.

**Comment by kchapple** [comment]
Remove it I suppose. I have no clue how it got there. I used submodules one time in a project about 10 years ago and that's it. They're a mess.
