### ISSUE TITLE
Clinical Reports enhancement

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/lh-ehr#1275]
The two new clinic reports need a useability enhancement.  The column head search filter boxes are TINY compared to the width of the columns.

Please make the search box dynamically sized to match or nearly match the width of the data below.

This will help make it obvious to users the these are meant to be used not graphic blips on the screen.

![dx-nhanes](https://user-images.githubusercontent.com/285835/47894320-6edb0500-de1f-11e8-9f99-99a8bcf4a049.png)

**Comment by tmccormi** [comment]
Files in question ... might be in the CSS though...

42494bd - diags pulls from lists, not issue_encounter table.  Can search by age range (#1269)
M       interface/reports/clinical_stats_by_demographics_report.php
M       interface/reports/lab_stats_by_demographics_report.php
M       interface/reports/username_report.php
M       library/ajax/clinical_stats_and_lab_stats_by_demographics_report_ajax.php

**Comment by jonathanzhang53** [comment]
I have found a fix! Will submit as a PR when I can claim a bug task :)
