### ISSUE TITLE
Table Tab Values Not Visible in Patient Demographics and Notes

### ISSUE THREAD

**Issue by jonathanzhang53** [LibreHealthIO/lh-ehr#1291]
**GIF:**
![tabserror](https://user-images.githubusercontent.com/41968151/48667593-65989c00-ea9f-11e8-8f72-f4de56f990f0.gif)

As you can see, the tabs do not have their values show up until they are clicked, and when a tab is clicked off of, the text disappears again.

**Replicate:**
Create a patient or have an existing one.
Go to that patient's profile by using Patient/Client > Add New/Search and clicking on their name.
Click the edit button next to demographics or notes.
The table will show up with the tab issue.

**Comments:**
Just installed EHR with XAMPP on Windows 10 home. I am using Chrome.
I inspected and there isn't a console issue related to the table values, so it's coded to perform like this.

**Comment by jonathanzhang53** [comment]
I can work on this

**Comment by jonathanzhang53** [comment]
@muarachmann 

I found the issue but I'm unsure how to approach it. I am still testing within the demographics table in the patient summary.

Each tab is a `li` and the `li` tab that has `current` class attached to it will have blue text. All other tabs have white text. When I inspect and add in the `current` class to each tab, the blue text appears. You can find the code for the demographics table in `lh-ehr/interface/patient_file/summary/demographics.php`.

I have found the styling in `lh-ehr/interface/themes/style_light.css`. 
![image](https://user-images.githubusercontent.com/41968151/48819704-d8f81300-ed16-11e8-8381-a3e06fe88b65.png)

The script that automates the removing and adding of the `current` class is in `lh-ehr/library/js/common.js`.
![image](https://user-images.githubusercontent.com/41968151/48819622-84549800-ed16-11e8-81ed-a2deac0dc426.png)

My idea is to make the current tab's text bold, so that the `current` class is still useful. However, when I try to edit the style_light.css and save changes, nothing appears on my side. For the changes, I just added the following:
![image](https://user-images.githubusercontent.com/41968151/48819638-95050e00-ed16-11e8-8973-1632c9f2b625.png)

As you can see, I changed the color of the regular tabs' text that aren't current to `#2672ec` and I added `bold` to the current tab's text. I went to user preferences and I am on the light theme. I refreshed the patient profile to get updates and nothing happens. Any idea why my changes aren't being loaded in?

**Comment by Trodrige** [comment]
@jonathanzhang53 try other themes and see what happens. Great work!!!

**Comment by Trodrige** [comment]
I opened an issue to handle this problem some time ago. 

Note: the different themes in the system make it a little difficult to work on styling most times. There is always a work around. Great job @jonathanzhang53

**Comment by jonathanzhang53** [comment]
@Trodrige thanks for the reply! I will definitely look into some more stuff tomorrow. It's bedtime for me. I still am confused on why changing style_light.css is not applying my changes though. I searched the whole project for tabNav styling and that's the only one I could find. 😢

**Comment by jonathanzhang53** [comment]
Well I have even tried deleting the whole style_light.css file and the formatting still stays the same. huh.

**Comment by jonathanzhang53** [comment]
Wow that took me like 6 hours to find one error in a css. Any tips for finding future bugs just to make it easier for me to narrow down what is causing the problem?

**Comment by Trodrige** [comment]
Sorry I couldn't help earlier @jonathanzhang53 

You just have to keep searching for the bugs and ask your questions here.
