### ISSUE TITLE
This theme's (Tan with no colors) button is not well displayed.

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/lh-ehr#1295]
<img width="1279" alt="librehealth_ehr" src="https://user-images.githubusercontent.com/16147419/48884951-bf45f100-ee26-11e8-99b3-44a5f90e93ca.png">

**Comment by jonathanzhang53** [comment]
@Trodrige check the theme_assets folder in interface/themes/theme_assets to see the images. They are not very good looking buttons :)

I can try and solve this by changing the button image. Will probably do it as a GCI task though 😄

**Comment by Trodrige** [comment]
Go ahead @jonathanzhang53

**Comment by jonathanzhang53** [comment]
Ok, so this exists in style_pdf, style_purple, style_tan_no_icons css files. Looking into it right now.

**Comment by jonathanzhang53** [comment]
@Trodrige Ok so this error exists also in the messages tab shown below:
![image](https://user-images.githubusercontent.com/41968151/48957617-46769000-ef1f-11e8-918e-c13b94469b19.png)

I was able to fix both of the buttons by adding a `<span>` and a `iframe` class. However, this fix would require me to go to every instance and do this. I can search the project for instances of `css_button` class and just make sure they're all formatted correctly. 
![image](https://user-images.githubusercontent.com/41968151/48957674-a9682700-ef1f-11e8-97eb-834943a0e559.png)


The alternative is to change the css, which may not apply evenly and would still require button hunting to apply a few fixes. Should I leave the css and correct throughout codebase?

**Comment by jonathanzhang53** [comment]
@muarachmann also (see above)

**Comment by jonathanzhang53** [comment]
Also, the `add profile picture` and `edit profile picture` buttons (depending on whether you have a pic uploaded or not) are encapsulated by a <label> tag, so those might require a change in css. I'll see what I can do.

**Comment by muarachmann** [comment]
@jonathanzhang53 ehmmmmm we did some UI revamping some time ago (team Alpha) never mind..... try adding `cp-positive` for buttons that make positive actions and `cp-negative` for negative actions. See what you get

**Comment by muarachmann** [comment]
This is a lil handy... check it here https://docs.google.com/document/d/1itWOLbC5xII8yArCaZE4LwzUpt_JwioKjdlg3yA8eg8/edit

**Comment by jonathanzhang53** [comment]
![image](https://user-images.githubusercontent.com/41968151/48960081-a1b07e80-ef2f-11e8-8751-82c187111615.png)

Ok, so this portion is fixed, but I bet there are other buttons across the codebase that are cut off also @muarachmann @Trodrige should I submit a PR for this one button fix or search across codebase more.

**Comment by jonathanzhang53** [comment]
## `css_button` class Issue List:

#### Directory- lh-ehr/interface/...

- patient_file/summary/demographics.php [FIXED]
- main/messages/messages.php [FIXED]
- Line 551 patient_file/encounter/superbill_custom_full.php*
- Lines 203, 206 patient_file/history/track_appointments.php*
- Lines 217 usergroup/usergroup_admin_add.php*

**Special:** Lines 521, 523 usergroup/usergroup_admin.php (cp-positive and cp-misc are messing up the buttons here) (I am able to fix by removing cp classes but I shouldn't right?)
![image](https://user-images.githubusercontent.com/41968151/48961503-a890be80-ef3a-11e8-88b8-f105a4964a5e.png)

#### Directory- lh-ehr/updater/templates...
- Line 47,68 updater_screen_four.html*
- Line 42 updater_screen_five.html*
- Line 18 developer_mode_progress.html*

*I am unable to access/find where the button appears
