### ISSUE TITLE
Lab Overview title not displaying

### ISSUE THREAD

**Issue by muarachmann** [LibreHealthIO/lh-ehr#1298]
Tab shows unknown on click of the Lab overview menu.

### Steps to reproduce this ###

Click on the following **Procedures > Lab Overview** 

### Expected behaviour ###
Lab overview tab should open with title Lab overview

### Actual behaviour ###
Shows unknown title tab bar

![screen shot 2018-11-24 at 7 44 51 am](https://user-images.githubusercontent.com/16350814/48965407-e20a0e00-efbc-11e8-9d12-a9757d423a93.png)

**Comment by jonathanzhang53** [comment]
cool! cool! more ehr issues!

**Comment by muarachmann** [comment]
@jonathanzhang53 can you handle this :)

**Comment by jonathanzhang53** [comment]
I made a commit to this, but I will make a PR when I claim the GCI bug task :)
