### ISSUE TITLE
Incorrect label on calendar tab after search panel closed

### ISSUE THREAD

**Issue by Vishwas-Adiga** [LibreHealthIO/lh-ehr#1301]
![normalcalendar](https://user-images.githubusercontent.com/28251020/49028132-b149f480-f1c7-11e8-85dc-40a3fec2b7f4.JPG)
Normal calendar tab
![searchmode](https://user-images.githubusercontent.com/28251020/49028133-b149f480-f1c7-11e8-9753-eca413b025cf.JPG)
Tab text changes when search button is clicked
![backtocalendar](https://user-images.githubusercontent.com/28251020/49028134-b149f480-f1c7-11e8-8e05-45f2a5742b1e.JPG)
Tab text doesn't revert to its original value when search panel is closed

**Comment by MigDinny** [comment]
working on this one!
