### ISSUE TITLE
FAB doesn't close when focus is lost

### ISSUE THREAD

**Issue by Vishwas-Adiga** [LibreHealthIO/lh-ehr#1302]
![fabnotclosing](https://user-images.githubusercontent.com/28251020/49028382-42b96680-f1c8-11e8-9e69-38329a180747.JPG)
The Floating Action button expands when hovered on, but doesn't collapse even when another button is clicked on. 
Expected behaviour: FAB collapses when another button is clicked, when the mouse is hovered over any other element, or when the action performed by the FAB is finished.

**Comment by punwai** [comment]
I've made a fix here https://github.com/LibreHealthIO/lh-ehr/pull/1303
