### ISSUE TITLE
Fields Not Filled Error Clears Form Data in Orders and Result Types

### ISSUE THREAD

**Issue by jonathanzhang53** [LibreHealthIO/lh-ehr#1310]
## Description

When you make a new top level in Orders and Result Types, you can purposely not fill out all the fields and save but it clears all the data that you have filled in.

## Reproduce

Login to EHR locally.
Go to Procedures > Configurations.
Click Add Top Level Button.
Fill out some information in Name or whatever you like, but leave a field blank.
Click save and see that it clears all the data.

## Fix

Some function is probably called that clears the data when the user cancels or something. Make sure the function is not attached to Save.

## GIF

![toplevel](https://user-images.githubusercontent.com/41968151/49196282-0153c300-f350-11e8-8a9f-733c0005cfc7.gif)

**Comment by jonathanzhang53** [comment]
I'll work on this for my GCI task.

**Comment by teryhill** [comment]
The system is telling you to fill out all the fields. Be careful that you don't fix a process and introduce a bigger problem.

**Comment by jonathanzhang53** [comment]
@teryhill I understand. This still qualifies as an issue right?

**Comment by teryhill** [comment]
@jonathanzhang53  that will be up to the stake holders of this community, I was just making an observation.

**Comment by jonathanzhang53** [comment]
@teryhill I see. I will see what I can do without tampering with the existing functionality :)

**Comment by jonathanzhang53** [comment]
I've looked through the code for this product iframe. It seems that the clearing of form data after a validation error is thrown is normal for forms like these. It isn't really an error in the code, just a feature that may or may not be useful if added in. Currently, there aren't any other errors besides filling in all the inputs, so closing this for now.

**Comment by muarachmann** [comment]
@jonathanzhang53 like terry said be careful not to introduce a bigger pb :)
