### ISSUE TITLE
Navbar is overlapped by Title

### ISSUE THREAD

**Issue by punwai** [LibreHealthIO/lh-ehr#1313]
How to recreate: 
Minimize the browser until the Title is overlapping with the navbar elements. This will Overlap the navbar elements. This breaks the hovering of the navbar.
![fix1](https://user-images.githubusercontent.com/28529491/49411927-9563c700-f762-11e8-9489-55f8c863d1ba.gif)

**Comment by punwai** [comment]
I will work on this

**Comment by muarachmann** [comment]
@punwai to what size are you resizing?

**Comment by punwai** [comment]
@muarachmann Around 3/4th of my screen

**Comment by punwai** [comment]
@muarachmann I've sent a pull request
