### ISSUE TITLE
Patient Export from Popups menu returns unexpected 404

### ISSUE THREAD

**Issue by bauripalash** [LibreHealthIO/lh-ehr#1327]
## Problem
While exploring the interface of the EHR, I tried clicking **Export** from **Popups** and got an unexpected 404.
Seems like it is trying to call an absent file `export_xml.php` from `custom` directory

### Screenshots: 
<img src="https://user-images.githubusercontent.com/16154204/49449616-4caf1b00-f801-11e8-8c69-51a38e2aabc2.png" width="50%">

**Comment by Trodrige** [comment]
If my memory isn't failing me here, this file was deleted. Just saying.

@bauripalash the same thing happens when you click on Popups->Import.

It appears custom/export.xml and custom/import.xml are missing.

**Comment by Trodrige** [comment]
It seems there's a couple of files missing from the system. Click on QA Measures-> XML Editor

<img width="1278" alt="librehealth_ehr" src="https://user-images.githubusercontent.com/16147419/49459714-f84f6f80-f7ef-11e8-85a4-9440ad110f51.png">

**Comment by bauripalash** [comment]
@Trodrige so best way to fix these?

**Comment by Trodrige** [comment]
We need to know what those tabs show when clicked and get these missing files. @teryhill @tmccormi  @aethelwulffe can say something here.

**Comment by teryhill** [comment]
![image](https://user-images.githubusercontent.com/4655366/49462058-279bb780-f7c3-11e8-9477-18359ce75846.png)

Got it on my system. May be some one thought the files were not needed and removed them.

**Comment by tmccormi** [comment]
I believe Art removed the programs as they do nothing useful for LibreEHR and were inherited from OpenEMR...  just edit the menu.json file to remove the selections, in my opinion.

**Comment by bauripalash** [comment]
@tmccormi You mean Here : https://github.com/LibreHealthIO/lh-ehr/blob/08c9e29bb1cce1c92c30b35d3d76b01d3025ded2/sites/default/menu_data.json#L982

**Comment by bauripalash** [comment]
@tmccormi @Trodrige Please take a look at the above mentioned PR
