### ISSUE TITLE
Cannot see all Facilities in Calendar Panel

### ISSUE THREAD

**Issue by KoniKodes** [LibreHealthIO/lh-ehr#1334]
![image](https://user-images.githubusercontent.com/18405001/49529402-c7605080-f86a-11e8-87b8-16fa8b2d4512.png)

There are two Facilities...

![image](https://user-images.githubusercontent.com/18405001/49529446-e1019800-f86a-11e8-9b93-c4def6d64852.png)

Only one is seen... So we can't toggle between the two.

**Comment by muarachmann** [comment]
@Konikodes are you logged in as an administrator?

**Comment by KoniKodes** [comment]
@muarachmann Yes, I am.

**Comment by tmccormi** [comment]
Check that the facilities that need to be seen have "Service Location" checked and that the Globals Feature "Restrict User to Facility" is turned off.

**Comment by KoniKodes** [comment]
Thank you so much! My problem was the "Restrict User to Facility" was checked.

It looks much better!

**Comment by tmccormi** [comment]
Great!
