### ISSUE TITLE
PDFs pages Unknown titles.

### ISSUE THREAD

**Issue by punwai** [LibreHealthIO/lh-ehr#1336]
<img width="513" alt="screen shot 2018-12-05 at 23 18 51" src="https://user-images.githubusercontent.com/28529491/49550622-2a41fe00-f8e4-11e8-9e02-e5da6fde7ee3.png">
On some PDF pages for example, Popups > Chart Label, Popups > Barcode Label and Popups > Address Label, the title is unknown

**Comment by robbyoconnor** [comment]
This is related to #1321
