### ISSUE TITLE
Patient/Client Add New Search shows blank "Unknown" screen. 

### ISSUE THREAD

**Issue by KoniKodes** [LibreHealthIO/lh-ehr#1344]
![image](https://user-images.githubusercontent.com/18405001/49664979-535baf00-fa08-11e8-976d-5042ad622a9a.png)

This makes it difficult to add a new patient...

**Comment by KoniKodes** [comment]
Inspector leads to new.php:
view-source:https://ehr.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
`{"label":"Patient\/Client","menu_id":"patimg","children":[{"label":"Finder","menu_id":"fin0","target":"fin","url":"\/interface\/main\/finder\/dynamic_finder.php","children":[],"requirement":0},{"label":"Add New\/Search","menu_id":"new0","target":"pat","url":"\/interface\/new\/new.php","children":[],"requirement":0},`

However, this is the code for it:
![image](https://user-images.githubusercontent.com/18405001/49666498-24940780-fa0d-11e8-9a86-7c28f43cc74f.png)

**Comment by punwai** [comment]
I will check this out.

**Comment by punwai** [comment]
How did you replicate this issue? It works fine for me 
<img width="834" alt="screen shot 2018-12-08 at 02 47 53" src="https://user-images.githubusercontent.com/28529491/49681063-b9d9df00-fa93-11e8-9ce6-e9936a63e9c3.png">

**Comment by KoniKodes** [comment]
https://ehr.librehealth.io/interface/login/login.php?site=docs
username: admin
password: documentationisawesome

Takes you to https://ehr.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT

I am having the issues from this site...

**Comment by muarachmann** [comment]
@KoniKodes we cant help if you are using the docs site... I think @tmccormi can get the latest codes to this site. As of now we cant replicate the issues you have simply because we have different codes running. Please bear with us. Hope Tony or Robby fixes this

**Comment by KoniKodes** [comment]
Thank you @muarachmann 
This is where Mr. Tony said to put the info. 
The only other way I can get it to look right is through the Inspector, one page at a time - and that is only temporary.

**Comment by tmccormi** [comment]
@muarachmann @aethelwulffe  This is a blocker for the OutReachy team, Can anyone address this rapidly?

**Comment by tmccormi** [comment]
PS: The latest code was deployed to the our demo and docs site.  So it should be identical.

**Comment by muarachmann** [comment]
@tmccormi on local it shows the tab. How come online it breaks

**Comment by muarachmann** [comment]
On it..

**Comment by tmccormi** [comment]
NOTE: there are no errors in the log files, so it has to be a JS thing, you can use the browser console tools to find this issue I bet

**Comment by muarachmann** [comment]
@tmccormi  Issue is the file was renamed to new comprehensive.php stuff so pointing the menu to that direction should have it solve. Making a PR ;)

**Comment by aethelwulffe** [comment]
Thank you.

Those dang names are so stupid...never can figure out what they are called!  Hint:  There are quite a few files involving encounters as well as demographics that are never called.  In the encounter form there is a file that has not ever been used, and has been there for ~17 years.  Search "Pennington".

**Comment by tmccormi** [comment]
You Rock @muarachmann !  Feel free to close this issue if it is now resolved.
