### ISSUE TITLE
User Profile Picture Not Displayed Properly on Navigation Bar

### ISSUE THREAD

**Issue by bauripalash** [LibreHealthIO/lh-ehr#1355]
## Problem : 
Profile Picture of a user is not displayed properly and breaking alignment. Which eventually makes the navigation bar worse.

### Screenshots :
![screenshot from 2018-12-08 17-57-02](https://user-images.githubusercontent.com/16154204/49685969-78891400-fb13-11e8-8fa4-128395a2c2f6.png)

**Comment by jonathanzhang53** [comment]
@bauripalash is this from the demo or local master branch? I can't seem to replicate.

![image](https://user-images.githubusercontent.com/41968151/49689658-c25d0480-fae9-11e8-88bd-269a419695f2.png)

**Comment by muarachmann** [comment]
@bauripalash please make sure you are working with latest version of the codes before making any PRs we wont want a backward compatibility stuff

**Comment by robbyoconnor** [comment]
Check using the code in the `master` branch please.

**Comment by bauripalash** [comment]
Apologise, Already Explained , What Was Happening in Rocket Chat
