### ISSUE TITLE
Formatting Issues in Add/Search Patient

### ISSUE THREAD

**Issue by jonathanzhang53** [LibreHealthIO/lh-ehr#1374]
Link: Patient->Search or Add Patient->Insurance
Work: - Change the font-color from red to black(default)
	-Give insurance form fields styling, space out the elements. For example give some space between select fields and the Add buttons

![image](https://user-images.githubusercontent.com/41968151/50305043-523e6f00-0457-11e9-8527-e1f4433d1146.png)

**Comment by jonathanzhang53** [comment]
I'll work on this. This was from UI Tasks from GCI.

**Comment by jonathanzhang53** [comment]
I also have a question about this. I'm seeing this 'required' class that is attached to most of the fields, but I can create a patient still by filling out only a few fields. The class is making text bigger and bold, which actually looks good (Face Sheet is example), but then you get to insurance and the text is small since it doesn't have a 'required' class. Not sure what to do here.

**Comment by punwai** [comment]
Its done at #1363
