### ISSUE TITLE
Unable to add Patients picture in Ubuntu

### ISSUE THREAD

**Issue by prondubuisi** [LibreHealthIO/lh-ehr#1384]
I am trying to add a patients picture but am getting this error 
![screenshot from 2019-01-14 17-41-08](https://user-images.githubusercontent.com/22311928/51126548-bae4f580-1823-11e9-88da-d82375184d55.png)

when I try creating the folder profile_pictures manually under the root directory I get the error 
![screenshot from 2019-01-14 17-45-20](https://user-images.githubusercontent.com/22311928/51126764-3e9ee200-1824-11e9-9b87-ec44b420e550.png)

Everything works well when I change the profile_pictures permission to 777 though

Is this the expected behaviour?

I am testing on ubuntu 18.04

**Comment by muarachmann** [comment]
@prondubuisi prior to this https://github.com/LibreHealthIO/lh-ehr/blob/master/INSTALL.md#setup yes you have to chmod. This gives me a doubt probably your docker installation didnot handle that. Please make all those directories writable for future puposes.

@robby did you handle this?

**Comment by robbyoconnor** [comment]
Is this critical?

**Comment by robbyoconnor** [comment]
I verified this -- your host system doesn't matter since this is running in Docker.

**Comment by robbyoconnor** [comment]
There's a handful of bugs that I can see.
