### ISSUE TITLE
Authenticated Unrestricted file upload when editing/updating patient profile picture

### ISSUE THREAD

**Issue by prondubuisi** [LibreHealthIO/lh-ehr#1401]
After a patients profile picture has been initially uploaded one can replace the profile picture with any type of file using the Edit Profile picture feature. 
![edit patient profile](https://user-images.githubusercontent.com/22311928/52161021-577e1300-26bf-11e9-81ef-78b9a98d765e.png)
![php file upload](https://user-images.githubusercontent.com/22311928/52161027-61077b00-26bf-11e9-8e7c-4bfde5007199.png)

**Comment by prondubuisi** [comment]
I will like to fix this bug, I its confirmed.

**Comment by aethelwulffe** [comment]
Isn't there a PR for this already? or was it just an issue?
-This one is a case of someone with superuser access being able to hack their own computer.  Still bad.

**Comment by prondubuisi** [comment]
> Isn't there a PR for this already? or was it just an issue?
> -This one is a case of someone with superuser access being able to hack their own computer. Still bad.

@aethelwulffe , I looked through, there is no PR for this, can I work on it?
