### ISSUE TITLE
Json parse error in Merger Encounter

### ISSUE THREAD

**Issue by MisterAwesome23** [LibreHealthIO/lh-ehr#1406]
![screenshot from 2019-02-15 03-21-38](https://user-images.githubusercontent.com/36367483/52821127-e9c8e280-30d3-11e9-8f98-2ded535c18b2.png)

On accessing Merger Encounter:
Status: parsererror, Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data php

For reference: Output of chrome console:
Uncaught TypeError: Cannot read property 'split' of undefined
    at r.fn.init.t.fn.(:8000/interface/main/tabs/anonymous function) [as iziModal] (http://localhost:8000/assets/js/iziModalToast/iziModal.min.js:6:24422)
    at main.php?url=TAB_ONE_DEFAULT:527

**Comment by muarachmann** [comment]
@MisterAwesome you can go ahead and fix this issue it has to do with the jquery version. That is a huge pb across EHR. we need to scale it up and use the latest stable version currently i think it is `3.1.1` if i am not mistaken. If you can submit a patch for that as well  it would be great. so we drop the other jquery versions across EHR in the `/assests` dir and making the application lighter :D

**Comment by muarachmann** [comment]
@MisterAwesome you can go ahead and fix this issue it has to do with the jquery version. That is a huge pb across EHR. we need to scale it up and use the latest stable version currently i think it is `3.1.1` if i am not mistaken. If you can submit a patch for that as well  it would be great. so we drop the other jquery versions across EHR in the `/assests` dir and making the application lighter :D

**Comment by muarachmann** [comment]
@MisterAwesome you can go ahead and fix this issue it has to do with the jquery version. That is a huge pb across EHR. we need to scale it up and use the latest stable version currently i think it is `3.1.1` if i am not mistaken. If you can submit a patch for that as well  it would be great. so we drop the other jquery versions across EHR in the `/assests` dir and making the application lighter :D

**Comment by aethelwulffe** [comment]
@MisterAwesome23 Thank you for the bug report.  Are you volunteering to fix this?

**Comment by MisterAwesome23** [comment]
Yes I would like to volunteer for this. The thing is I already have opened #1399 and being a newbie to this environment am proceeding at my own pace and might need a bit more help than obvious. But I'd definitely like to work on this issue after all - Finding a bug and fixing it yourself is a bliss :)

**Comment by muarachmann** [comment]
@MisterAwesome23 feel free to drop your comments here or in the chat. Well definitely help.

**Comment by muarachmann** [comment]
@MisterAwesome23 are u still on this? If you have any issues on solving this let us know. we might be of help :)

**Comment by MisterAwesome23** [comment]
Yes I want to this. I'll get onto to ASAP sorry for the slack and delay. I'll post doubts and comment on this thread it self :)

**Comment by muarachmann** [comment]
great then

**Comment by MisterAwesome23** [comment]
![screenshot from 2019-02-26 00-51-01](https://user-images.githubusercontent.com/36367483/53362644-ab97b280-3960-11e9-9d1b-214407e2b749.png)

I found all occurrences for "Merge Encounters"
All JSON files seem fine. 

I did not 100% understand how this is related to jquery version and to be fixed. 

Is it something like this, that the error is because of reference to an unstable jquery and has to be shifted to 3.1.1 to fix it? Is it so?

Can you please elaborate a bit more, I did put in time to google and stackoverflow but couldn't associate. I am pretty big newbie, please bear with me :D

**Comment by muarachmann** [comment]
That was my guess from first sight and I think it will do :-)

**Comment by MisterAwesome23** [comment]
So the JQuery is placed in /assests right?
But where exactly is it being referenced for this particular case or "Merge encounters" any clue?

**Comment by muarachmann** [comment]
sure @MisterAwesome23

**Comment by MisterAwesome23** [comment]
I tried hunting the current .js file using:
var script = document.currentScript;
var fullUrl = script.src;

(Source: https://stackoverflow.com/questions/2255689/how-to-get-the-file-path-of-the-currently-executing-javascript-code)

I tried alerting the output and it shows "null" 
Maybe that is the very issue of having no currently running .js on accessing MergeEncounters.
![screenshot from 2019-02-27 00-33-29](https://user-images.githubusercontent.com/36367483/53439505-28419400-3a28-11e9-9744-291250c8489a.png)

**Comment by muarachmann** [comment]
Hey please steps on arriving to this screen

**Comment by MisterAwesome23** [comment]
After selecting "Merge Encounters" tab and encountering the json parse error. I went onto inspect element and accessed the console.
Typed in:
var script = document.currentScript;
var fullUrl = script.src;
alert(script);

To display the current js path which seems to be null.

**Comment by muarachmann** [comment]
@MisterAwesome23 i mean accessing the merge encounters menu. I cant find it. maybe i messed up with my test branch?

**Comment by aethelwulffe** [comment]
This is code from my company.  It is contained in /modules/merge_encounters.
All assets are self-contained within that directory.

**Comment by Ngai-E** [comment]
@MisterAwesome23  I came across this issue and I would like to contribute into fixing it but I wish to know if it was solved already because I am having a hard time reproducing it both on my local instance and on the docs site.

**Comment by MisterAwesome23** [comment]
@Ngai-E as far as a go the issue is still up for a solve. Kindly go ahead with you contributions to fix this : )

**Comment by muarachmann** [comment]
@Ngai-E , @MisterAwesome23 i have no issues with this. Surely try clearing your cached files etc. and hard resetting your browers. Here is what i get

![Screen Shot 2019-03-29 at 4 57 18 PM](https://user-images.githubusercontent.com/16350814/55246622-dcac2100-5245-11e9-87ab-c93700ec740b.png)

![Screen Shot 2019-03-29 at 4 56 58 PM](https://user-images.githubusercontent.com/16350814/55246625-e03fa800-5245-11e9-941a-27e27db148ac.png)

**Comment by aethelwulffe** [comment]
I also am having no problems with the module.  I can't produce the error, nor can two other folks.  It may be related to an install issue....jUst don't know.
