### ISSUE TITLE
Able to add invalid email when adding pharmacy

### ISSUE THREAD

**Issue by Ngai-E** [LibreHealthIO/lh-ehr#1413]
A)  **Outreachy Username:** elizabeth

B) **Issue Title:** Able to add invalid email when adding pharmacy.

C) **Bug Report Date**: Thursday, 28th  February 2019.

D) **Site Affected:** Documentation Site and NHANES

E) **OS/ Browser Used**: Chrome  on Ubuntu 16.04

F) **Which Workflow Module in LHEHR**: Administration => Practice Settings

G) **Steps to Reproduce the Bug:**
   1. Login to the LibreHealth EHR platform.
   2. Move on to the Administration menu item and select Practice from the drop down options.
   3. Click on Pharmacies and then click on Add a Pharmacy.
   4. Fill in a pharmacy Name (which is required).
   5. Fill in a wrong Email say “thisIsWrongEmail Right?”.
   6. Click on the Save button and it will be saved successfully to the database without throwing a 
      validation error.

H) **At Point of the Bug, the Expected Behavior:** The expected behavior was to prompt the user to input a valid email address before clicking save.

I) **Details of What Actually Happened:** Typed in an invalid email address when adding a pharmacy and it was accepted.

J) **Provide Relevant Screenshot and Explain the Screenshot:** 
![image](https://user-images.githubusercontent.com/22508583/53660744-eb131700-3c5e-11e9-8fff-480125537a89.png)
Illustration 1: Select Practice from Administration

![image](https://user-images.githubusercontent.com/22508583/53660880-3299a300-3c5f-11e9-92b7-2fb5d8a30e66.png)
Illustration 2: Select Pharmacies

![image](https://user-images.githubusercontent.com/22508583/53660897-3c230b00-3c5f-11e9-979a-931795a07c5b.png)
Illustration 3: Click on Add a Pharmacy button

![image](https://user-images.githubusercontent.com/22508583/53660911-480ecd00-3c5f-11e9-9081-e2dbf3660c93.png)
Illustration 4: Fill in invalid email as shown in this example and click save which will then save successfully

K) Estimation of The Bug Severity: Module continues with ongoing errors (Critical).

**Comment by muarachmann** [comment]
thanks for your report @Ngai-E we are here to help you fix this is you want

**Comment by Ngai-E** [comment]
> thanks for your report @Ngai-E we are here to help you fix this is you want

Yes muarachmann I would love to contribute to the fixing this and any other issues if permitted. I am good at HTML/CSS, JavaScript, PHP, MySQL just to name a few and I am willing to learn any other requirements to work on LibreHealth EHR. Waiting on instructions on how to proceed thanks.

**Comment by muarachmann** [comment]
@Ngai-E sure. use the inspector tool to guide you on seeing where the resource file is located. If you have any issues ping me in the chats or just drop it here :)

**Comment by Ngai-E** [comment]
> @Ngai-E sure. use the inspector tool to guide you on seeing where the resource file is located. If you have any issues ping me in the chats or just drop it here :)

sure, thanks.

**Comment by Ngai-E** [comment]
Hi @muarachmann I think i have a solution for this issue please. I made this change to controller.php file for add pharmacy and i think it works now but the test has only been done locally.
[controller.php.zip](https://github.com/LibreHealthIO/lh-ehr/files/2942907/controller.php.zip)

**Comment by muarachmann** [comment]
@Ngai-E closing this since solved
