### ISSUE TITLE
 An unclear modal box appears while creating new XML for MIPS.

### ISSUE THREAD

**Issue by Priyanka488** [LibreHealthIO/lh-ehr#1418]
**A) **Outreachy username :**** priyanka.yadav

**B) Issue title :** An unclear modal box appears while creating new XML for MIPS.

**C) Site affected:** The documentation site

**D) Bug report date :** March 6, 2019

**E) OS/ browser used:** Windows/Chrome

**F) Which workflow module in LHEHR :** “Create MIPS Report” under “QA Measures”

**G) Steps to reproduce the bug :** 

        1. Login with your account credentials.
        2. Click on QA Measures from the top menu , and select Create MIPS Report.
        3. Enter Begin date , End date and other details.
        4. Click on Submit. 
        5. Now click on New XML for MIPS.
        6. The modal box appears.

**H) At point of bug, the expected behavior :** On clicking the button , “New XML for MIPS”, a modal box with opaque background should appear , such that the instructions are clearly visible and are easy to follow for the user .

**I) Details of what actually happened :** On clicking the button , “New XML for MIPS”, an unclear modal box appeared with a transparent background , making the instructions written inside it , completely unreadable for the user .

**J) Provide relevant screenshots :**
        
       a. Entering details and clicking on submit.
![screenshot 139](https://user-images.githubusercontent.com/33698440/53902811-0d929f00-4068-11e9-9cdd-6021986831ea.png)

       b. The New XML for MIPS button  :
![screenshot 142](https://user-images.githubusercontent.com/33698440/53902836-2307c900-4068-11e9-9ec3-db25d2522d8f.png)

       c. After clicking the New XML for MIPS button , the modal box appears :
![screenshot 141](https://user-images.githubusercontent.com/33698440/53902867-33b83f00-4068-11e9-9126-9aebe9d33ba7.png)

**K) Estimation of the bug severity :** module function continues with ongoing errors.

**Comment by muarachmann** [comment]
yes @konikodes , @Priyanka488 this is a bug..

**Comment by KoniKodes** [comment]
@Priyanka488 Please try to duplicate this on the NHANES site.

**Comment by Priyanka488** [comment]
@konikodes The unclear model box appears on the NHANES site too.

**Comment by KoniKodes** [comment]
Ok @muarachmann and @Priyanka488 
It seems to me that we need fix the modal so that it is not transparent. Then the user can read the text and follow any directions.
Do I understand correctly?

**Comment by aethelwulffe** [comment]
Transparent modal windows over other text is...sub-optimal...

**Comment by Priyanka488** [comment]
@muarachmann I am not able to find concerned css files, the text is printed through htmlecho, and the inspector lists no css file either.

May I replace the htmlecho part with p tags and enclose it in html tag and add inline css ?
