### ISSUE TITLE
Patient Documents Showing Black screen

### ISSUE THREAD

**Issue by muarachmann** [LibreHealthIO/lh-ehr#1430]
From the latest pull of EHR. i noticed the patient document screen all shows blank. As a consequence one cannot upload any files to the `sites/xxxx/directory`. See below

![Screen Shot 2019-03-11 at 10 13 20 PM](https://user-images.githubusercontent.com/16350814/54158651-43120080-444b-11e9-879c-c49d7dc37d16.png)

Console output is blank too
![Screen Shot 2019-03-11 at 10 19 02 PM](https://user-images.githubusercontent.com/16350814/54158834-bca9ee80-444b-11e9-8c66-319c24eda2ff.png)

@aethelwulffe , @Trodrige do you please have this error too

**Comment by aethelwulffe** [comment]
Can't re-test right now, but can you check your permissions for the new photo directory (which is not on the list of stuff normally handled by vhost settings for /sites/*).  Also check the logs on your machine.  If nothing is coming up in console, then the code from the multiple PR's has just gotten mangled.

**Comment by muarachmann** [comment]
Ok Art, Thanks. I will do so and check my logs too

**Comment by muarachmann** [comment]
@aethelwulffe here are my Logs not sure why it is showing that

`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Undefined offset: 14 in /Applications/MAMP/htdocs/lh-ehr/controllers/C_Document.class.php on line 1092`
`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Only variables should be passed by reference in /Applications/MAMP/htdocs/lh-ehr/controllers/C_Document.class.php on line 1069`
`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Undefined offset: 0 in /Applications/MAMP/htdocs/lh-ehr/controllers/C_Document.class.php on line 1092`
`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Only variables should be passed by reference in /Applications/MAMP/htdocs/lh-ehr/controllers/C_Document.class.php on line 1069`
`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Undefined offset: 5 in /Applications/MAMP/htdocs/lh-ehr/controllers/C_Document.class.php on line 1092`
`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Only variables should be passed by reference in /Applications/MAMP/htdocs/lh-ehr/controllers/C_Document.class.php on line 1069`
`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Undefined offset: 10 in /Applications/MAMP/htdocs/lh-ehr/controllers/C_Document.class.php on line 1092`
`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Undefined offset: 4 in /Applications/MAMP/htdocs/lh-ehr/controllers/C_Document.class.php on line 1092`
`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Undefined offset: 1 in /Applications/MAMP/htdocs/lh-ehr/controllers/C_Document.class.php on line 1092`
`[13-Mar-2019 08:09:50 UTC] PHP Notice:  Undefined property: C_Document::$message in /Applications/MAMP/htdocs/lh-ehr/templates/documents/general_list.php on line 39`

**Comment by aethelwulffe** [comment]
Strict?
C_document lines 1091 and 1092 show:
 $icon = "file3.png";
            if (is_array($categories[$id])) {
Lots of commits related to this recently.  I need to stop everything and back up and test myself.  Individual branches have worked, but I have not tested the integrated whole in master.

**Comment by muarachmann** [comment]
this now works on my end had myself a fresh copy @aethelwulffe closing this
