### ISSUE TITLE
Performing patient Ledger search keeps displaying error message

### ISSUE THREAD

**Issue by Ngai-E** [LibreHealthIO/lh-ehr#1441]
A) **Outreachy Username:**  elizabeth

B) **Issue Title**: Can not select search patient Ledger in module Report – Financial -     Patient Ledger By Date .

C) **Bug Report Date**: March 14, 2019.

D) **Site Affected**: Documentation Site and NHANES

E) **OS/ Browser Used**: Chrome  on Ubuntu 16.04

F) **Which Workflow Module in LHEHR**: Report – Financial - Patient Ledger By Date

G) **Steps to Reproduce the Bug:**
1. Login to LibreHealth EHR.
2. Select Reports menu item.
3. Hover over Financial drop down option and click on Patient Ledger By Date.
4. Choose a From and To date range  (Optional to reproduce bug).
6. Select a patient and click on Submit.

H) **At Point of the Bug, the Expected Behavior**: User expects to see a list of patient ledgers displayed in an orderly manner, say, a table for example.

I) **Details of What Actually Happened**: User keeps getting the error message ‘No data to display. Select patient and try search again.’ and whether or not the user selects a patient who visited the hospital in a particular selected date range, user still is unable to see patient ledger with the same error message ‘No data to display. Select patient and try search again.’.

J) **Provide Relevant Screenshot and Explain the Screenshot:**

			
	
![image](https://user-images.githubusercontent.com/22508583/54392455-068f1080-46a8-11e9-8c23-c1ea27af844e.png)
Illustration 1: showing visual  steps to reproduce bug 

![PatientLedger](https://user-images.githubusercontent.com/22508583/54392618-6e455b80-46a8-11e9-853c-bb326ed8c99f.png)
Illustration 2: Error message still persist even after selecting patient with correct date.

 

K) **Estimation of The Bug Severity:** Module function continues with ongoing errors (Critical).

**Comment by aethelwulffe** [comment]
Patient has to have authorized billing and payments for this report to display data.  We will look into the queries it runs to display the same.
  Despite the feelings of certain parties, we cannot use the Documentation or NHANES site to do troubleshooting, as there is no access to the database (phpmyadmin specifically) to determine the state of the data or make direct changes to affect that.  Thus, using a local copy with some data is a good idea for anyone wishing to actually troubleshoot or do development.
  I will hunt what I can after work.

**Comment by Ngai-E** [comment]
> Patient has to have authorized billing and payments for this report to display data. We will look into the queries it runs to display the same.
> Despite the feelings of certain parties, we cannot use the Documentation or NHANES site to do troubleshooting, as there is no access to the database (phpmyadmin specifically) to determine the state of the data or make direct changes to affect that. Thus, using a local copy with some data is a good idea for anyone wishing to actually troubleshoot or do development.
> I will hunt what I can after work.

Thanks @aethelwulffe I will be waiting

**Comment by KoniKodes** [comment]
> we cannot use the Documentation or NHANES site to do troubleshooting, as there is no access to the database (phpmyadmin specifically) to determine the state of the data or make direct changes to affect that. Thus, using a local copy with some data is a good idea for anyone wishing to actually troubleshoot or do development.

So this means what I told Priya was wrong - this was found in the local instance but I told her to use Docs Site:
Under Patient/Add new/search
Go for Search
Search a patient
Select a patient. Now the patient information is displayed at the top left corner, and the name of the module changes to patient name also.
Edit the Demographics.
Change the name of the patient and save the changes.
The module name changes but the top left corner stays same. It still shows the old name.

This is an actual issue that should be reported? How do I know when to have them report from where?

**Comment by aethelwulffe** [comment]
No, nothing wrong there. Just for fixing actual issues, often we have to look at what data is being used, which can't be done on the docs site directly.  Yes, you need to use the same site/settings for documentation purposes.
OK, first, the patient ledger in this instance was accessed via dems, right?
Edit the dems, save, look for name change does not refresh the top fields.  I get confused when you folks say "module", as the top panel is an iframe, and each frame/tab open is another iframe displaying another web-page.
  So, the top frame does not instantly refresh when you change the patient's name.  Without a top_restore_session call from demographics_full.php, I don't think that behavior is going to change easily.  If you do that, then it has more complex interactions.  The next time the patient is searched and displayed, the active patient ID will reflect the corrected name.  This could be "fixed" but there is some question as to how badly that needs doing.  Some of these things are just behavior it is best to document vs. overloading the code with complex behavior, as re-running the session data may impact other things.  I dunno.  Would have to look into it.
  That is a separate issue from this patient ledger not displaying data.  I think that the primary issue is that the NHANES data is not replete enough with fake billing data (I commented on this before) to allow someone to fully document the EHR.  Billing and all that is *very important* to folks that like to get a paycheck out of their nursing job, so documenting the billing configuration and use is very near and dear to the hearts of the practice managers implementing the EHR.
RE THIS ISSUE:
The patients, when they do not have billing/payment data will not display results either doing the patient ledger report from the patient demographics face-sheet or by selecting Reports>Financial>patient ledger.  This is a feature, not a bug at this point if there is nothing recorded in the ar_activity or ar_session tables for that patient.
HOWEVER, there are still bugs of a sort.
![image](https://user-images.githubusercontent.com/553751/54444268-c74cd800-4718-11e9-99e3-d56f5cfc0d1d.png)
You will see that the version from Reports>Financial>Patient Ledger by Date has a patient select box.  It is microscopic (right tab in view above.
You will also see that the date picker update added recently does not retain the date input from the report.  It should.

I am sorry if I have kinda been inaccurate with some of this.  I am trying to work while getting constant phone calls and other communication as well as reviewing this.  Not going to be doing my best and deepest work!

**Comment by KoniKodes** [comment]
Thank you. I know you are busy and appreciate your time and info you share. 

I will send both applicants to read this, so they each understand what they are looking for, and where.

**Comment by Ngai-E** [comment]
i> No, nothing wrong there. Just for fixing actual issues, often we have to look at what data is being used, which can't be done on the docs site directly. Yes, you need to use the same site/settings for documentation purposes.
> OK, first, the patient ledger in this instance was accessed via dems, right?
> Edit the dems, save, look for name change does not refresh the top fields. I get confused when you folks say "module", as the top panel is an iframe, and each frame/tab open is another iframe displaying another web-page.
> So, the top frame does not instantly refresh when you change the patient's name. Without a top_restore_session call from demographics_full.php, I don't think that behavior is going to change easily. If you do that, then it has more complex interactions. The next time the patient is searched and displayed, the active patient ID will reflect the corrected name. This could be "fixed" but there is some question as to how badly that needs doing. Some of these things are just behavior it is best to document vs. overloading the code with complex behavior, as re-running the session data may impact other things. I dunno. Would have to look into it.
> That is a separate issue from this patient ledger not displaying data. I think that the primary issue is that the NHANES data is not replete enough with fake billing data (I commn ented on this before) to allow someone to fully document the EHR. Billing and all that is _very important_ to folks that like to get a paycheck out of their nursing job, so documenting the billing configuration and use is ve ry near andis dear to ecthe hearts of the pgaractice managers implementing the EHR.
> RE Tccoon HIS ISSUE:us
> The patients, when they do not have billing/payment data will not display results either doing the patient ledger report from the patient demographics face-sheet or by selecting Reports>Financial>patient ledger. This is a feature, not a bug at this point if there is nothing rec orded in the ar_activity or ar_session tables for that patient.
> HOWEVER, there are still bugs of a sort.
> ![image](https://user-images.githubusercontent.com/553751/54444268-c74cd800-4718-11e9-99e3-d56f5cfc0d1d.png)
> You will see that the version from Reports>Financial>Patient Ledger by Date has a patient select box. It is microscopic (right tab in view above. 
> You will also see that the date picker update added recently does not retain the date input from the report. It should.
> 
> I am sorry if I have kinda been inaccurate with some of this. I am trying to work while getting constant phone calls and other communication as well as reviewing this. Not going to be doing my best and deepest work!

I understand how tight schedule can be @aethelwulffe. I will like to mention that, the issue with this report is not to check whether or not there is a billing data. But what I expect to happen if no billing data was found, is an appropriate response such as 'Sorry no billing data was found for this patient' instead of 'No data to display. Select Patient and try again.' meanwhile a patient was selected. User can get confused as to the actual cause of failure.

**Comment by aethelwulffe** [comment]
You are completely correct.  The error message stinks.  Make more gooder
or suggest the text specifically and delegate to someone.
