### ISSUE TITLE
 “Incorrect password” appears when password isn’t even changed

### ISSUE THREAD

**Issue by Priyanka488** [LibreHealthIO/lh-ehr#1451]
**A) Your outreachy username :** priyanka.yadav

**B) Issue title :** “Incorrect password” appears when password isn’t even changed.

**C) Site affected:** The documentation site , NHANES site.

**D) Design Flaw report date :** March 19, 2019

**E) OS/ browser used:** Windows/Chrome

**F) Which workflow module in LHEHR :**“Pass Phrase” under “Miscellaneous”.

**G) Steps to reproduce the design flaw :**

1. Login with your account credentials.
2. Click on “Pass Phrase” under “Miscellaneous”.
3. Click on Save
4. A message appears on top of iframe- “Incorrect password”.

**H) At point of design flaw, the expected behavior :** When the user has not changed the password, “Save” button should not display anything.

**I) Details of what actually happened :** On clicking on Save button, a message appears on top of iframe - “Incorrect password”.

**J) Provide relevant screenshots :**

**On clicking Save button -** 

![hh](https://user-images.githubusercontent.com/33698440/54620222-d7074c00-4a8b-11e9-9716-1b83602eaf42.PNG)

**K) Estimation of the flaw severity :** module function continues with workaround.

**L) Possible Solution :** Validation of password fields for blank values, before comparing the saved original password with the entered one.

**Comment by muarachmann** [comment]
@Priyanka488 this is correct. Please you can go ahead and submit a PR
