### ISSUE TITLE
Close Transaction Popup button Missing (Replace with iziModal)

### ISSUE THREAD

**Issue by muarachmann** [LibreHealthIO/lh-ehr#1456]
Currently, the trasaction popup has no way of closing it and added to that the old popup is ugly and has to be replaced with iziModal. See below

![Screen Shot 2019-03-21 at 2 52 43 AM](https://user-images.githubusercontent.com/16350814/54729539-760f6f00-4b84-11e9-8a1b-8bc46aa72672.png)

**Comment by aethelwulffe** [comment]
Make sure to check the popup in other themes, and Look at DATA in an old version before implementing a new thingie so you get a good before and after.

**Comment by ishita20** [comment]
@muarachmann I would like to work on this.

**Comment by muarachmann** [comment]
Thanks @ishita20 , this is no longer valid was fixed. Closing this
