### ISSUE TITLE
Two Close Button on Modal

### ISSUE THREAD

**Issue by Ngai-E** [LibreHealthIO/lh-ehr#1460]
A) **Outreachy Username:**  elizabeth

B) **Issue Title**: Track Appointments modal shows redundant close buttons.
C) **Design Flaw Report Date:** March 21, 2019.

D) **Site Affected**: Documentation Site and NHANES

E) **OS/ Browser Used:** Chrome  on Ubuntu 16.04

F) **Which Workflow Module in LHEHR:** Patient/Client => Track Appointments

G) **Steps to Reproduce the Bug:**
1. Login to LibreHealth EHR.
2. Select Track Appointments from the Patient/Client menu item.
3. Under the Last Name, click on any patient’s name.
4. Under the Date column, click on any date and a modal box will appear.

H) **At Point of the Design Flaw, the Expected Behavior**: User expects to see one option to close the modal box which is automatically provided by the modal which appears.

I) **Details of What Actually Happened:** User gets to find an extra ‘Close’ button which ends up doing the same thing as the default one. This is as a result of adding an extra HTML close button link in the modal body.

J) **Provide Relevant Screenshot and Explain the Screenshot:**
![close](https://user-images.githubusercontent.com/22508583/54768272-1f934680-4bff-11e9-978c-8875a81f674c.png)
Illustration 1: Modal contains two closing options (redundant)

K) **Estimation of The Design Flaw Severity:** Distracting or confusing but work flow can continue correctly (Minor).

L) **Proposed Solution:**
This can be solve by removing the link tag circled in the screen shot below.
![image](https://user-images.githubusercontent.com/22508583/54767979-8e23d480-4bfe-11e9-9664-70cd0abc060c.png)
Removing the tag will then result into this better view below.
![image](https://user-images.githubusercontent.com/22508583/54768011-9ed44a80-4bfe-11e9-8e1e-95fa82552b34.png)

**Comment by muarachmann** [comment]
Sure this is a very good catch. Nice work @Ngai-E

**Comment by aethelwulffe** [comment]
PR is up for this.
