### ISSUE TITLE
 Can Not Filter Patient Clinic Reports

### ISSUE THREAD

**Issue by Ngai-E** [LibreHealthIO/lh-ehr#1461]
A) **Outreachy Username:**  elizabeth

B) **Issue Title**: Can not filter patient clinic reports.

C) **Bug Report Date**: March 20, 2019.

D) **Site Affected:** Documentation Site and NHANES

E) **OS/ Browser Used**: Chrome  on Ubuntu 16.04

F) **Which Workflow Module in LHEHR:** Reports => Clients => Clinical

G) **Steps to Reproduce the Bug:**
1. Login to LibreHealth EHR.
2. Select Clients drop down option from the Reports menu item and click on Clinical.
3. On the module that appears, leave all the enteries as default and click on the Submit button (note the results that are displayed).
4. Now, on the ‘Gender’ drop down menu select ‘female’ and click on the ‘Submit’ button  (note that the displayed results).
5. Set ‘Gender’ to ‘unassigned’, set ‘Patient ID’ to ‘6’  and ‘Facility’ to ‘North East Clinic’ , then,  click on the ‘Submit’ button  (note that the displayed results), .

H) **At Point of the Bug, the Expected Behavior:** 
After going through steps 1 and 2 mentioned above, user expects the following to happen afterwards in the proceeding steps.

1. In step 3 above, user expects to see a list of all patient records in all the facilities.
2. In step 4, user expects to see a list of all female patients records in all the facilities.
3. In step 5, user expects to see just one patient record with the ‘Patient ID’ specified belonging to ‘North East Clinic’. 

I) **Details of What Actually Happened**: User gets all the patients in all facilities, male or female as result no matter the search criteria specified in work flow.

J) **Provide Relevant Screenshot and Explain the Screenshot:**
![image](https://user-images.githubusercontent.com/22508583/54770084-d7762300-4c02-11e9-9088-24f34709bbb6.png)
Illustration 1: showing all patient clinic reports
![image](https://user-images.githubusercontent.com/22508583/54770122-e9f05c80-4c02-11e9-91fa-15b9869c2acf.png)
Illustration 2: Search for female patients also showing male patients.
![image](https://user-images.githubusercontent.com/22508583/54770216-12785680-4c03-11e9-806c-a5c5db7f30ad.png)
Illustration 3: Search for a unique patient with ID 6 in North East Clinic still displaying all patients with different IDs

K) **Estimation of The Bug Severity**: Module function continues with ongoing errors (Critical).

L)  **Possible Solution:** I make to following suggestions to implement this fix;
1. When user clicks on the ‘Submit’ button, user selected inputs should be validated and stored successfully.
2. A validated query should be made to the back end with user inputs used to implement SQL clauses..

**Comment by muarachmann** [comment]
Nice catch @Ngai-E keep them coming
