### ISSUE TITLE
Cannot Plot Graph for Patient Encounter Data

### ISSUE THREAD

**Issue by Ngai-E** [LibreHealthIO/lh-ehr#1462]
A) **Outreachy Username**:  elizabeth

B) **Issue Title**: Error Plotting Graph.

C) **Bug Report Date**: March 23, 2019.

D) **Site Affected**: Documentation Site and NHANES

E) **OS/ Browser Used**: Chrome  on Ubuntu 16.04

F) **Which Workflow Module in LHEHR**: ‘Patient/Client’ => ‘Finder’.

G) **Steps to Reproduce the Bug**:
1. Login to LibreHealth EHR.
2. Select ‘Finder’ drop down option from the ‘Patient/Client’ main menu item.
3. Click on patient name ‘Aaronson’ having ‘Patient ID’ 84 under ‘Last Name’ from the entries shown.
4. Hover over ‘Past Encounter List’ (top right of page) and select encounter #4, marked ‘2019-02-18 Established Patient’. 
![image](https://user-images.githubusercontent.com/22508583/54873446-ad755a00-4dd6-11e9-90f8-1e710de39514.png)
5. Click on the ‘Show track history’ button shown in the screenshot above (Note: there might be more than one and you can click on any).
6. Next click on ‘encounter data’ and ‘data for all encounters’ buttons one after another after selecting the checkbox directly above the two buttons.

H) **At Point of the Bug, the Expected Behavior**: User expects to see a nicely plotted graph of data selected somewhere on the screen.

I) **Details of What Actually Happened**: User gets and error message in a pop up alert on clicking both buttons as shown in ‘illustration 1’ below. 

J) **Provide Relevant Screenshot and Explain the Screenshot**:
![image](https://user-images.githubusercontent.com/22508583/54873458-f3322280-4dd6-11e9-82eb-70814fbfd1a8.png)
Illustration 1: Showing pop up error circled in red

K) **Estimation of The Bug Severity**: Module function continues with ongoing errors (Critical).

L) **Possible Diagnosed Problem**: From the error message shown above, it was discovered that the current page was trying to access a url which does not exist, /opt/ehr/modules/openflashchart/graph_track_anything.php. Also from chrome dev tools, it was discovered that the page was not only trying to access one file that does not exist but many others, as listed below;
1. [https://ehr.librehealth.io/opt/ehr/modules/openflashchart/graph_track_anything.php](url)
2. [https://ehr.librehealth.io/opt/ehr/modules/openflashchart/js/json/json2.js](url)
3. [https://ehr.librehealth.io/opt/ehr/modules/openflashchart/js/swfobject.js](url)
	
Testing above links  individually in a new browser tab will result to an error.
![image](https://user-images.githubusercontent.com/22508583/54873488-650a6c00-4dd7-11e9-96be-74180290525e.png)
Illustration 2: Chrome Network tab(inspector tool) showing broken links in red

M) **Proposed Solution**: After testing broken links 1 to 3 above and searching for where these files actually sit in the directory tree ( searching in local instance cloned from LibreHealth GitHub repo), it was noticed that no directory /opt/ehr/modules/openflashchart/ exist on the server /modules/openflashchart/ existed. So, taking out the ‘/opt/ehr’ from each of the urls above would work!!
Correct links are;
1. [https://ehr.librehealth.io/modules/openflashchart/graph_track_anything.php](url)
2.  [https://ehr.librehealth.io/modules/openflashchart/js/json/json2.js](url)
3. [https://ehr.librehealth.io/modules/openflashchart/js/swfobject.js](url) 

Testing above links  individually in a new browser tab will work.

**Comment by Ngai-E** [comment]
@muarachmann I tested this on firefox but still had the same problem mentioned in the report, maybe something else was causing it the last time but now the reason is a 404 error.

**Comment by muarachmann** [comment]
I am not on PC now. Maybe later in the evening

**Comment by muarachmann** [comment]
A 404 error shows the resource file is not available. Verify this in the
code base

**Comment by muarachmann** [comment]
@Ngai-E i don't have this issue on the docs site. I just went through

**Comment by KoniKodes** [comment]
@muarachmann Could it be because you have full admin rights and Elizabeth doesn't?

**Comment by muarachmann** [comment]
oh keep forgetting this stuff. Maybe yes maybe no. We really need some alerts for ACL in the repo so users don't stay stranded @aethelwulffe ?

**Comment by KoniKodes** [comment]
I like that idea...

**Comment by muarachmann** [comment]
Yeah true. Or rather don't show them the options rather than raising some expectations

**Comment by Ngai-E** [comment]
Ok. So its not an issue for now right? Or should i work on hiding the option from unauthorized user?

**Comment by muarachmann** [comment]
Hello Eli.. try testing this feature on your local instance with admin
privileges to see if it works see this if -
https://github.com/LibreHealthIO/lh-ehr/files/2779465/Track.anything.draft.pdf.
If so then the possible cause could be the ACL.
We have to discuss on how to better go about it

Regards

**Comment by aethelwulffe** [comment]
If the user can see an encounter, they should be able to see this stuff. 
That is the ACL issue that should not exist.  Easy enough to track down to where the acl_check() function cuts someone out.

**Comment by muarachmann** [comment]
@Ngai-E is this still open and valid?

**Comment by Ngai-E** [comment]
@muarachmann I still have this problem. I enabled flash plugin on chrome. I can successfully plot a graph when I click on 'Plot selected Items'. But when i click on **'Show track history**' then click on encounter data I get the error above. Please check it out. It happens on the docs site. 

Please dont click on the 'Plot selected Items' button that works fine. instead click on **'Show track history**' then **'encounter data'**. That is where the problem is.

**Comment by aethelwulffe** [comment]
How up to date is the docs site?

**Comment by Ngai-E** [comment]
@KoniKodes  graph plot shown above is not testing the issue.

**Comment by aethelwulffe** [comment]
Right.  Understand.

**Comment by Ngai-E** [comment]
> How up to date is the docs site?

I guess it was updated few days ago by @robbyoconnor because i can not see the some of the bugs that were fixed on the site anymore. For example the issue with merged PR #1443 6 days ago, no longer occurs on the docs site.

**Comment by Ngai-E** [comment]
I do not think it is ACL. I think its the file path that does not exist as stated in the pop up alert message.

**Comment by muarachmann** [comment]
Errr @Ngai-E please give me a sample patient with plot graph on the docs site. Surely some 500 error is occuring

**Comment by Ngai-E** [comment]
> Errr @Ngai-E please give me a sample patient with plot graph on the docs site. Surely some 500 error is occuring

3.  ‘Aaronson’ having ‘Patient ID’ 84 
4.  #4, marked ‘2019-02-18 Established Patient’.

**Comment by Ngai-E** [comment]
Its the same procedure on the issue report above maybe you missed a step while reading it.

**Comment by muarachmann** [comment]
Oh i see. I fixed the plot graph and not the show track issue. Okay will make a patch for it

**Comment by muarachmann** [comment]
I cant see the encounter stuff for the patient when i click show track history

![Screen Shot 2019-05-15 at 5 33 14 PM](https://user-images.githubusercontent.com/16350814/57792708-94828880-7737-11e9-898a-c1ef0e8fbbe5.png)

**Comment by muarachmann** [comment]
Okay fine i could replicate this. On it

**Comment by Ngai-E** [comment]
> I cant see the encounter stuff for the patient when i click show track history
> 
> ![Screen Shot 2019-05-15 at 5 33 14 PM](https://user-images.githubusercontent.com/16350814/57792708-94828880-7737-11e9-898a-c1ef0e8fbbe5.png)

That is because you are using an encounter without data. Please use the encounter with date  **‘2019-02-18 Established Patient’.**

**Comment by Ngai-E** [comment]
![image](https://user-images.githubusercontent.com/22508583/57793148-8c771880-7738-11e9-97de-05667c54bdb6.png)
this one

**Comment by muarachmann** [comment]
Yeah fine i could replicate this. I am working on this

**Comment by Ngai-E** [comment]
ok
