### ISSUE TITLE
Cannot Save Dated Reminders

### ISSUE THREAD

**Issue by Gicheha** [LibreHealthIO/lh-ehr#1468]
**A) Outreachy UserName:** gicheha

**B) Issue Title:** On the Messages and Reminder center, Trying to save or send a dated reminder leads to a data error.

**C) Date Issued:** April 19, 2019

**D) OS/Browser Tested:** Windows 10, Google Chrome Version 72.0.3626.119 (Official Build) (64-bit)

**E) Testing Site:** The Error occurs in Messages and Reminder Center on the reminders section when the send a dated reminder option is selected.

**F) Steps to Reproduce the Bug:** The following steps can be used to reproduce the error:
             

-  Log in to the EHR module

              

- Select the Messages option on the menu

             

-  On the Messages and reminders center screen, under the Reminders header, expand 
    the “show reminders” option

             

-  Select the send a dated reminder option 

           

-    Link the dated reminder to a patient if applicable

              

- Select the recipient(s)

             

-  Type in a message then press send message

 
**G) Expected Behaviour:** The module is supposed to send the message and make it viewable on 
     the logs 
**H) What Actually Happens:** A data error is shown regardless of the nature of data that is input

**I) Bug Severity:** The bug severity is major as the user cannot go beyond that point.

**J) Screenshots:**
![image](https://user-images.githubusercontent.com/9331796/56455793-cd635380-636b-11e9-87e4-b05be4c9db14.png)
Select the Messages Menu Option

![image](https://user-images.githubusercontent.com/9331796/56455796-e2d87d80-636b-11e9-85c9-09a8ce777ba7.png)
Expand the show reminders section

![image](https://user-images.githubusercontent.com/9331796/56455802-069bc380-636c-11e9-8d7b-0a6197e57066.png)
Select the Send Dated reminder and fill in the details

![image](https://user-images.githubusercontent.com/9331796/56455807-1e734780-636c-11e9-8098-b815a1d33caa.png)
Optional link to patient screen

![image](https://user-images.githubusercontent.com/9331796/56455812-321eae00-636c-11e9-81f2-c01e5d7fe9f0.png)
Fill in the rest of the details

![image](https://user-images.githubusercontent.com/9331796/56455816-45317e00-636c-11e9-971e-6aa784b94016.png)
Clicking on the send message leads to a data error

**K) Proposed Solution:** From the Google developer console, the errors that cause the data error notification are as follows:

![image](https://user-images.githubusercontent.com/9331796/56455835-8c1f7380-636c-11e9-9429-a4e7fe20ca0e.png)
The errors displayed on the developer console

**L) Affected File(s):** The following files are affected by the errors:
	[project_root]/interface/main/dated_reminders/dated_reminders_add.php

**M) Proposed Fix:** To fix the error, the code snippet including the JQuery library should be included before any other javascript script is included. In this case, the jquery-2.2.0 script in the library/js folder was included in the affected file:

![image](https://user-images.githubusercontent.com/9331796/56455840-9f324380-636c-11e9-8dc4-bdf6408cfb91.png)
Snippet showing the proposed changes

**N) Result(s):** In the local test implementation, the dated reminders are added as expected 

![image](https://user-images.githubusercontent.com/9331796/56455851-b2451380-636c-11e9-9666-40b61a31311e.png)
Successful sending of dated reminders

**Comment by muarachmann** [comment]
@Gicheha please provide screenshots of output and related screen from first guess i think the jquery library is not compatible and thats a pb with LH we have many versions this needs to be revamped to 3.3.1 i think

**Comment by Gicheha** [comment]
> 
> 
> @Gicheha please provide screenshots of output and related screen from first guess i think the jquery library is not compatible and thats a pb with LH we have many versions this needs to be revamped to 3.3.1 i think

@muarachmann I had some problem with adding images to the editor window but that is sorted

**Comment by Gicheha** [comment]
@muarachmann yes I think the Jquery dependancy is the problem

**Comment by muarachmann** [comment]
@Gicheha upgrade the JS script to 3.3 this is my fault. When i included izi in the repo. It should behave well

**Comment by MisterAwesome23** [comment]
I did try this with and without link to the patient. Both of my messages are successfully available in log.
![LibreHealth#1468](https://user-images.githubusercontent.com/36367483/57410111-92846b00-7207-11e9-82e5-5e729807950c.png)

Am I doing something wrong reproduce the bug?
This is my screen before pressing  "Send this message"

![#1468](https://user-images.githubusercontent.com/36367483/57410244-e68f4f80-7207-11e9-8f3b-9a980f17ab43.png)

**Comment by KoniKodes** [comment]
This is what I see in the Inspector:
![image](https://user-images.githubusercontent.com/18405001/57411618-f294f600-71a2-11e9-9204-1e0ca1c30be4.png)

**Comment by KoniKodes** [comment]
@MisterAwesome23 Did you try to Send a Reminder instead of a Message?

**Comment by muarachmann** [comment]
@KoniKodes all looks good on my end. I made that patch. can you confirm you have a  green izi popup ? @MisterAwesome23

**Comment by MisterAwesome23** [comment]
Yes I did have a green tiny popup after pressing the send message button. Do you want me to screenshot that?

**Comment by KoniKodes** [comment]
@muarachmann So we are good to close this issue?

**Comment by muarachmann** [comment]
yeah closing this
