### ISSUE TITLE
Modify .gitignore to exclude all directories in /sites dir except default

### ISSUE THREAD

**Issue by muarachmann** [LibreHealthIO/lh-ehr#1477]
When installing EHR for first or n times, you might want to have multiple instances where you can access via some `site_id=xxxx` doing this will lead to creation or mirror of an already existing sites dir in the `/sites` dir.  We dont need this to show up on git commits

- ignore all folders in `/sites` except for default site 
NB - sqlconfig.php for `/sites/default` is not needed equally you can check this #1388

**Comment by aethelwulffe** [comment]
If we do not need sqlconf.php, then let's kill it.  Gitignore should specifically ignore the existence of that file, even if it is in /default.

**Comment by prondubuisi** [comment]
@muarachmann what should be done here?

**Comment by Patil2099** [comment]
@muarachmann  Can I work on this ?

**Comment by muarachmann** [comment]
Sure @Patil2099 feel free to work on any issues around. If you are looking for friendly beginner issues i can point some out.

**Comment by Patil2099** [comment]
@muarachmann  It would be a great help. Thanks. Please point out some for me

**Comment by muarachmann** [comment]
Here you go
https://github.com/LibreHealthIO/lh-ehr/labels/good%20first%20issue
