### ISSUE TITLE
Undefined index (state) in setup.php file causes errors at local install

### ISSUE THREAD

**Issue by KoniKodes** [LibreHealthIO/lh-ehr#1480]
Operating System: Windows 8 
Error occurs on both Wamp and Xampp:
![image](https://user-images.githubusercontent.com/18405001/57861143-edd7cf80-77aa-11e9-9868-fd3861a409a9.png)
![image](https://user-images.githubusercontent.com/18405001/57861163-f8926480-77aa-11e9-94dd-d2401f2b1a1d.png)

Did not expect to see an error. I did expect to click on the Continue button and be taken to the LibreHealth EHR Setup Screen.

When I ignored the error and clicked on Continue, I saw more errors:
![image](https://user-images.githubusercontent.com/18405001/57861459-81110500-77ab-11e9-8349-fec69c8f75db.png)

The Severity is Critical to me, as I can not continue to install locally.

Suggested solution: Define state for setup.php.
![image](https://user-images.githubusercontent.com/18405001/57861614-c33a4680-77ab-11e9-850c-1922d73b6d5a.png)

**Comment by KoniKodes** [comment]
Along with the line above, setup.php mentions **state**
line 42: ` echo "<form method='post'><input type='hidden' name='state' value='0'>" .
    "Site ID: <input type='text' name='site' value='default'>&nbsp;" .
    "<input type='submit' value='Continue'><br></form><br>\n";
  `
line 93: `else if ($state > 3) {
  // State 3 should have created the site directory if it is missing.
  die("Internal error, site directory is missing.");
}`

setup.php initially calls two files:
password_hashing which does not mention state at all.
Installer.class which does not mention state at all.

I know php is not my language, but shouldn't somewhere in one of those three files be a statement such as `state = 0`?

**Comment by muarachmann** [comment]
Hi Toni the error you are having is due to the fact that error_reporting /
display errors is enabled in your php.ini file in xampp.
Please turn/switch it off. Please do these steps
https://github.com/LibreHealthIO/lh-ehr#on-windows

**Comment by KoniKodes** [comment]
Thank you @muarachmann 
I have finally got it installed!

**Comment by muarachmann** [comment]
Glad you could make it
