### ISSUE TITLE
Incorrect Description for Property Setting

### ISSUE THREAD

**Issue by mhn94** [LibreHealthIO/lh-ehr#1484]
A) **Outreachy Username:** maggie.negm
B) **Issue Title:** Incorrect Description for Property Setting
C) **Report Date:** 6/26/2019
D) **Sites Affected:** Documentation Site
E) **OS/Browser Used:** Chrome browser in Linux OS
F) **EHR Workflow Module:** Edit Global Settings
G) **Steps to Reproduce the Issue:**

1. Select “Administration” from the main menu.
2. Select “Globals” under "Administration."
3. Select the “Calendar” tab in the "Edit Global Settings" module.
4. Scroll down until you reach "Auto-Create New Encounters" property setting, and hover over this property setting to see its description.

H) **Expected Behavior:** The "Auto-Create New Encounters" property setting's description should say something along the lines of "Automatically create a new encounter when the '@ Arrived' appointment check in status is selected."
I) **What Actually Happened:** The "Auto-Create New Encounters" property setting's description currently states: "Automatically create a new encounter when an appointment check in status is selected."
J) **Screenshots with Explanation:**
Hovering over the "Auto-Create New Encounters" property setting within Globals shows its description.
![auto-create-new-encounters-description](https://user-images.githubusercontent.com/8771586/60221357-594f9b00-9847-11e9-9630-4abb1c98884b.png)
Using Google Chrome's Inspect to view corresponding code:
![auto-create-encounters-inspect](https://user-images.githubusercontent.com/8771586/60292378-f57eae00-98ea-11e9-9ff9-c813c002e0c1.png)
K) **Estimation of Severity:** cosmetic defect only; has no effect on Workflow or Module's actual function

**Comment by muarachmann** [comment]
Closing this.Thanks @mhn94  for the fix
