### ISSUE TITLE
Flow Board Property Choice Typo

### ISSUE THREAD

**Issue by mhn94** [LibreHealthIO/lh-ehr#1509]
A) **Outreachy Username:** maggie.negm
B) **Issue Title:** Flow Board Property Choice Typo
C) **Report Date:** 10/02/2019
D) **Sites Affected:** Documentation, NHANES
E) **OS/Browser Used:** Chrome browser in Linux OS
F) **EHR Workflow Module:** Flow Board
G) **Steps to Reproduce the Issue:**
    

1. Select “Flow Board” from the main menu (if Flow Board isn’t already open by default).
2. Select the gear icon in the upper-left corner of the Flow Board window.
3. Select the drop-down list under the “Ending Date for Patient Flow Board” setting.

H) **Expected Behavior:** The choice should read “Three Months Ahead.”
I) **What Actually Happened:** The choice actually reads “Three Months AheadThree Months Ahead.”
J) **Screenshots with Explanation:**
After going to the Flow Board local settings and selecting the drop-down list under “Ending Date for Patient Flow Board,” the fourth choice is mistyped – it’s printed twice.
![Issue1](https://user-images.githubusercontent.com/8771586/66150467-3faab600-e5e3-11e9-82bb-40e85e7f14c1.png)
The following is the associated code within Chrome Inspector:
![Issue-1-2](https://user-images.githubusercontent.com/8771586/66150489-4c2f0e80-e5e3-11e9-93ef-fc412890977e.png)
K) **Estimation of Severity:** Minor - distracting or confusing but workflow can continue correctly
M) **Solution:** Within the patient_tracker.php file (/interface/patient_tracker/patient_tracker.php) on line 259, remove the text, “Three Months Ahead,” that is directly before the closing <option> tag.

**Comment by muarachmann** [comment]
Correct and thanks @mhn94
