### ISSUE TITLE
Security Concern - LibreHealth EMR does not automatically time-out users

### ISSUE THREAD

**Issue by FlaviaKebirungi** [LibreHealthIO/lh-ehr#1511]
- Outreachy Username: **FlaviaKebirungi**
- Issue Title: Security Concern - LibreHealth EMR does not automatically time-out users
- Report Date: 05-Oct-2019
- OS/Browser Used: Windows/Chrome

**Issue:**
The Application seems not to automatically time-out for logged in users which might a security concern for accessing sensitive health resources.

**Comment by FlaviaKebirungi** [comment]
Already solved!

**Comment by aethelwulffe** [comment]
Actually, it does.

Check global settings.
