### ISSUE TITLE
Flow Board - Option Grammatical Error

### ISSUE THREAD

**Issue by FlaviaKebirungi** [LibreHealthIO/lh-ehr#1513]
**A) Outreachy Username:** FlaviaKebirungi

**B) Issue title:** Flow Board - Option Grammatical Error

**C) Report Date:** 5-Oct-2019

**D) Sites Affected:** Documentation

**E) OS/ browser used:** Windows 10 – Chrome and Firefox

**F) EHR Workflow module:** Flow Board

**G) Steps to Reproduce the Issue:**

1.	Login to the LibreHealth EHR.
2.	Click on “Flow Board” in the menu.
3.	Click on the gear icon in the top left corner of the “Flow Board” window.
4.	The third option “Show Exam Room Patient Flow Board” has a grammar error.

**H) Expected Behavior:** I expected the option to read “Show Exam Room in Patient Flow Board”.

**I)  What Actually Happened:** The option read “Show Exam Room Patient Flow Board”

**J)  Screenshots with Explanation:**

![Flow Board Show Exam Room Typo](https://user-images.githubusercontent.com/56150011/66246438-9da3de80-e746-11e9-9091-1f2e3a4e7a56.png)
 
The figure above shows the error marked red

**K) Estimation of Severity:** Minor: distracting or confusing but workflow can continue correctly

**L) Solution:** The solution is to correct the grammar in the affected file (https://github.com/LibreHealthIO/lh-ehr/blob/master/interface/patient_tracker/patient_tracker.php) on line 240.

**Code with error (line 240):**
<label><input type="checkbox" name="ptkr_show_room" value="1" <?php if($GLOBALS['ptkr_show_room']=='1') echo "checked"; ?>><?php echo xlt("**Show Exam Room Patient Flow Board**"); ?></label>

**Suggested corrected code:**
<label><input type="checkbox" name="ptkr_show_room" value="1" <?php if($GLOBALS['ptkr_show_room']=='1') echo "checked"; ?>><?php echo xlt("**Show Exam in Room Patient Flow Board**"); ?></label>

**Comment by KoniKodes** [comment]
You lose 3 points for not having the inspector image as I said during feedback.
I really need for you to read what I say, and do it as I asked.
