### ISSUE TITLE
Invalid Date Range Accepted Within Flow Board

### ISSUE THREAD

**Issue by mhn94** [LibreHealthIO/lh-ehr#1514]
A) **Outreachy Username:** maggie.negm
B) **Issue Title:** Invalid Date Range Accepted Within Flow Board
C) **Report Date:** 10/04/19
D) **Sites Affected:** Documentation, NHANES
E) **OS/Browser Used:** Chrome browser in Linux OS
F) **EHR Workflow Module:** Flow Board
G) **Steps to Reproduce the Issue:**

1. Select “Flow Board” from the main menu (if Flow Board isn’t already open by default).
2. Enter an invalid date range within the Flow Board. (If the Flow Board doesn’t accept a date range, it can be changed in the local or global settings of the Flow Board.)
       
H) **Expected Behavior:** An expected scenario is to have the form prevent users from entering an invalid date range and to output a message that informs users of their mistake and how to fix it.
I) **What Actually Happened:** The form accepts an invalid date range.
J) **Screenshots with Explanation:**
The following image shows the Flow Board accepting the following invalid date range: 2019-10-01 to 2019-09-04.
![invalid-date-range-size-w-outline](https://user-images.githubusercontent.com/8771586/66247649-36a60b80-e6ed-11e9-8bb4-3a4b70742d19.png)
The following is the associated code within Chrome Inspector:
![invalid-date-range-chrome-inspector-w-outline](https://user-images.githubusercontent.com/8771586/66247656-40c80a00-e6ed-11e9-9f70-4dbcee3423e0.png)
K) **Estimation of Severity:** Critical – module function continues with ongoing errors
M) **Solution:** A form validater function needs to be created that will check for valid input before the form is submitted. If the input is invalid, a popup message will appear letting the user know that the input is invalid and to try again.

Similar Issues: #1499 & #1415

**Comment by muarachmann** [comment]
Use iziToast for this

**Comment by muarachmann** [comment]
Done!
