### ISSUE TITLE
Flow Board - Option Grammatical Error

### ISSUE THREAD

**Issue by FlaviaKebirungi** [LibreHealthIO/lh-ehr#1516]
A) Outreachy Username: FlaviaKebirungi

 B) Issue title: Flow Board - Option Grammatical Error

C) Report Date: 5-Oct-2019

D) Sites Affected: Documentation

E) OS/ browser used: Windows 10 – Chrome and Firefox

F) EHR Workflow module: Flow Board

G) Steps to Reproduce the Issue:

1.	Login to the LibreHealth EHR.
2.	Click on “Flow Board” in the menu.
3.	Click on the gear icon in the top left corner of the “Flow Board” window.
4.	The third option “Show Exam Room Patient Flow Board” has a grammar error.

H) Expected Behavior: I expected the option to read “Show Exam Room in Patient Flow Board”.

I)  What Actually Happened: The option read “Show Exam Room Patient Flow Board”

J)  Screenshots with Explanation:
 
![Flow Board Show Exam Room Typo](https://user-images.githubusercontent.com/56150011/66254410-84cc1500-e7a8-11e9-969b-efd46436416b.png)

The figure above shows the error marked red

K) Estimation of Severity: Minor: distracting or confusing but workflow can continue correctly

L) Solution: The solution is to correct the grammar in the affected file:

![Flow Board Show Exam Room Typo2](https://user-images.githubusercontent.com/56150011/66254399-65cd8300-e7a8-11e9-99f2-b03bad0e4416.png)

**Comment by muarachmann** [comment]
okay :0 u can use [github markups](https://guides.github.com/features/mastering-markdown/) to beautify things :)

**Comment by Ngai-E** [comment]
Thanks @FlaviaKebirungi  please fix it if you can. The message is really confusing.

**Comment by KoniKodes** [comment]
@FlaviaKebirungi Much better, thank you.

**Comment by muarachmann** [comment]
Was this ever fixed @FlaviaKebirungi ? Yess  i think in #1517
