### ISSUE TITLE
Duplicate Fields and Typo in Addr Book

### ISSUE THREAD

**Issue by HenriettaWilla** [LibreHealthIO/lh-ehr#1520]
A) Outreachy Username: NDum.
B) Issue Title: Duplicate Fields and Typo in Addr Book
C) Report Date: 10/06/19.
D) Sites Affected: Documentation Site.
E) OS/Browser Used: Chrome browser in Linux OS.
F) EHR Workflow Module: “Add New” button which is found in “Addr book” which is under “Miscellaneous” menu group. The same issue is also encountered in "Addr book" found under "Administration" in the main menu.
G) Steps to Reproduce the Issue:
Login with your account details.
Click on the menu group “Miscellaneous”.
Click on the “Addr Book” under “Miscellaneous”.
Click on the “Add New” button.
View the duplicate fields “City”, “State/country”, and  “Postal code” . Also, the label “State/country” was wrongly spelled as “State/county”.
Same issue also occurs on "Addr Book" found under "Administration" on the menu group
H) Expected Behaviour:
I expected to see three fields for City, State/country and postal code. Furthermore, I expected to see the label for country spelled as “country”.
 I) What Actually Happened: The fields for city, state/country and postal code were duplicated. And again, the label for country was spelled as “county”.
J) Screenshots with Explanation:

![image](https://user-images.githubusercontent.com/38100233/66270743-e34bce80-e84e-11e9-8cf1-9db8cb9dc1a6.png)
Figure 1

![image](https://user-images.githubusercontent.com/38100233/66270754-04142400-e84f-11e9-92ac-979ad3f73391.png)

Figure 2

Figure 1 above shows the duplicate fields marked in red and the typo error marked in green.
Figure 2 shows the issues and the chrome inspector showing where the issue is coming from.
K) Estimation of Severity: Minor: distracting or confusing but workflow can continue correctly.

L) Solution: The solution is to remove the duplicated fields and correct the typo error.

**Comment by KoniKodes** [comment]
Good call on both locations.
Now, can you write the code that will fix this?

**Comment by HenriettaWilla** [comment]
hello @KoniKodes 
yes I am working on it

**Comment by KoniKodes** [comment]
Okay Great!
Thank you.

**Comment by Ngai-E** [comment]
Great please fix it.

**Comment by muarachmann** [comment]
Closing this, fixed in #1526
