### ISSUE TITLE
Missing Word in Flow Board Setting Description

### ISSUE THREAD

**Issue by mhn94** [LibreHealthIO/lh-ehr#1523]
A) **Outreachy Username:** maggie.negm
B) **Issue Title:** Missing Word in Flow Board Setting Description
C) **Report Date:** 10/07/2019
D) **Sites Affected:** Documentation, NHANES
E) **OS/Browser Used:** Chrome browser in Linux OS
F) **EHR Workflow Module:** Flow Board
G) **Steps to Reproduce the Issue:**

    

1. Select “Flow Board” from the main menu (if Flow Board isn’t already open by default).
2. Select the gear icon in the upper-left corner of the Flow Board window.
       
H) **Expected Behavior:** The setting description should read “Flag Double Booked Appt in Patient Flow Board.”
I) **What Actually Happened:** The description actually reads “Flag Double Booked Appt in Flow Board.” It’s missing the word “Patient.” Otherwise, it isn’t consistent with the other property setting descriptions.
J) **Screenshots with Explanation:**
After going to the Flow Board local settings, the sixth property setting description is missing the word “Patient.”
![missing-word-w-outline](https://user-images.githubusercontent.com/8771586/66359562-a31b4780-e945-11e9-8055-d8fda5b43646.png)
The following is the associated code within Chrome Inspector:
![missing-word-console-w-outline](https://user-images.githubusercontent.com/8771586/66359592-c5ad6080-e945-11e9-9a35-48d26f71f1d0.png)
K) **Estimation of Severity:** Trivial - cosmetic defect only; has no effect on Workflow or Module's actual function
M) **Solution:** Within the patient_tracker.php file (/interface/patient_tracker/patient_tracker.php), add the word “Patient” in the property setting description in the “ptkr_flag_dblbook” checkbox label in the “pt_settings” form. It will then read “Flag Double Booked Appt in Patient Flow Board.”

**Comment by Ngai-E** [comment]
yes @mhn94  it should be consistent with the rest. Thank you.
