### ISSUE TITLE
Duplicate "Test" on Flow Board Category

### ISSUE THREAD

**Issue by HenriettaWilla** [LibreHealthIO/lh-ehr#1525]
A) Outreachy Username: NDum.
B) Issue Title: Duplicate "Test" on Flow Board "Category"
C) Report Date: 10/06/19.
D) Sites Affected: Documentation Site.
E) OS/Browser Used: Chrome browser in Linux OS.
F) EHR Workflow Module: Duplicate "Test" on Flow Board Category. When I drop it down, I see Test twice. On the console the line affected is “option value = 16”.
G) Steps to Reproduce the Issue:
Login with your account details.
Click on the menu group “Flow Board”.
Click on the select element corresponding to “Category”.
View the duplicate option “Test”.
H) Expected Behaviour:
I expected to see the option “Test” just once.
 I) What Actually Happened: The option “Test” was duplicated.
J) Screenshots with Explanation:
![image](https://user-images.githubusercontent.com/38100233/66437109-d41c7a80-ea20-11e9-8eba-80f26ed09115.png)
Figure 1

![image](https://user-images.githubusercontent.com/38100233/66437130-e26a9680-ea20-11e9-9d03-f13b44f40a9b.png)
Figure 2

Figure 1 above shows the duplicate option "Test" under Category
Figure 2 shows the chrome inspector indicating where the issue is coming from.
K) Estimation of Severity: Minor: distracting or confusing but workflow can continue correctly.

L) Solution: The solution is to remove the duplicated option.

**Comment by KoniKodes** [comment]
@HenriettaWilla 
In section G and H:
"Text" should be "Test". Just as it is seen in the image. Please change this report to reflect that and then create the PR.

**Comment by HenriettaWilla** [comment]
ok thanks @KoniKodes. I tried to rectify the issue but the clone repository does not have such error

**Comment by HenriettaWilla** [comment]
The categories were different from the one online

**Comment by muarachmann** [comment]
status??
