### ISSUE TITLE
Unreadable text on the submit button on Flow board panel. 

### ISSUE THREAD

**Issue by yamamashakaa** [LibreHealthIO/lh-ehr#1530]
A) Outreachy Username: yamama  
B) Issue title: Unreadable text on the submit button on Flow board panel. 
C) Report Date: 10/13/2019. 
D) Sites Affected: Documentation Site. 
E) OS/ browser used: Firefox and chrome browser on Windows10 OS.   
F) EHR Workflow module: When I was looking for patient’s appointment for specific provider. 
G) Steps to Reproduce the Issue:  
1) login to your account. 
2) Click on the Flow board item which is the second item in the top menu. 
3) Do appointments filtering by choosing the provider, other criteria and the date range then click the submit button (Note that the white text on the blue submit button is readable ). 
4) After clicking submit button for the first time, try to do another search you will notice that the text on the button is unreadable because its color become blue (Same as the background) after the first click. 
H)Expected Behavior: I expected to read submit text on the button every time I need it . 
I) What Actually Happened: The text Submit disappeared because it becomes blue as the background.   
J) Screenshots with Explanation:   
This is how the text appear when it has been clicked before 
![bughunt_01](https://user-images.githubusercontent.com/16443315/66722611-aa949200-ee18-11e9-9336-09b3bb2be03d.png)
K) Estimation of Severity:  Minor: distracting or confusing but workflow can continue correctly.  
M) Solution: The solution for this issue is to keep the text white after being visited. Change the color of the visited link to white like the screen shot below and you can make it specific to links inside  
.cp-submit so other links won’t be affected) .cp-submit a :visited 
![bughunt_02](https://user-images.githubusercontent.com/16443315/66722634-e891b600-ee18-11e9-8d41-c20b527ff48a.png)

**Comment by jonathanzhang53** [comment]
From when I worked with this codebase, I can probably guess that this is an issue with the css themes in EHR (inconsistency and overriding). 

Probably best to just leave these be until a universal theme is propped up.

**Comment by muarachmann** [comment]
Yes @jonathanzhang53 :) Nice seeing you around!, we look forward to having one theme `Prism`

**Comment by yamamashakaa** [comment]
yest, it is just the text color button in  the tan theme style sheet.
While testing I did not notice that there are multiple themes and in the tan theme  the red over the blue was so hard on eyes (while hovered) and the blue over blue while visited was not readable at all
 Looking forward to the universal theme
