### ISSUE TITLE
Duplicate Modules Open in the Same Screen

### ISSUE THREAD

**Issue by mhn94** [LibreHealthIO/lh-ehr#1531]
A) **Outreachy Username:** maggie.negm
B) **Issue Title:** Duplicate Modules Open in the Same Screen
C) **Report Date:** 10/13/19
D) **Sites Affected:** Documentation, NHANES
E) **OS/Browser Used:** Chrome browser in Linux OS
F) **EHR Workflow Module:** Calendar, Flow Board, and other default module options (except Messages)
G) **Steps to Reproduce the Issue:**
It depends on which modules open by default once a user logs in. In this example, let’s assume the “Calendar” and “Flow Board” modules are already opened by default.

1. Select “Calendar” from the main menu.
2. Select “Flow Board” from the main menu.
       
H) **Expected Behavior:** After trying to open another instance of an already opened module, the already opened module should stay open, but refresh itself.
I) **What Actually Happened:** A duplicate module opens. (However, if you try to open the module again, the second window refreshes itself.)
J) **Screenshots with Explanation:**
In this example, the default modules that are opened are Calendar and Flow Board.
![open-default-modules](https://user-images.githubusercontent.com/8771586/66723412-eb73b300-ede6-11e9-8faa-04ad155b6271.png)

1. Select “Calendar” from the main menu.
![main-menu-calendar-outline](https://user-images.githubusercontent.com/8771586/66723424-02b2a080-ede7-11e9-820c-765a02414dc8.png)
Another Calendar module opens.
![duplicate-modules-1-w-outline](https://user-images.githubusercontent.com/8771586/66723432-19f18e00-ede7-11e9-8e1c-6095b55001d1.png)

2. Select “Flow Board” from the main menu.
![main-menu-flowboard-outline](https://user-images.githubusercontent.com/8771586/66723435-2a096d80-ede7-11e9-9c51-2d18c06db2b8.png)
Another Flow Board module opens.
![duplicate-modules-2-w-outline](https://user-images.githubusercontent.com/8771586/66723440-355c9900-ede7-11e9-8082-d12c4a15115d.png)

The following is the associated code within the Chrome Inspector:
![chrome-inspector-code-w-outline](https://user-images.githubusercontent.com/8771586/66723446-43121e80-ede7-11e9-8931-6f4d0a6dcf05.png)

K) **Estimation of Severity:** Critical – module function continues with ongoing errors
M) **Solution:** Pass a $_Request PHP superglobal variable in each URL mention that will be processed in each file to determine if a module is already opened or not. If module is already opened, refresh the module. Otherwise, open a new module.

Same Issue: #1420

**Comment by muarachmann** [comment]
> M) Solution: Pass a $_Request PHP superglobal variable in each URL mention that will be processed in each file to determine if a module is already opened or not. If module is already opened, refresh the module. Otherwise, open a new module.

Hmmmmmm have you had a look at the codebase that handles this

**Comment by mhn94** [comment]
Yes. I started by looking at the Messages module, since it's the only modules out of all the default module options that doesn't have this issue. I noticed that it uses a superglobal variable to prevent the issue from happening.

**Comment by mhn94** [comment]
Change of plans. After familiarizing myself with the code base some more, I was able to identify the root cause: the navigateTab() function that determines if a tab is already opened was not able to correctly identify default tabs that were open. So I have a solution that fixes this!

**Comment by aethelwulffe** [comment]
1.  Sometimes, you WANT two copies of the same report run, such as with
different search criteria.  This is true with several items.

2.  The name/target in the menu.json for each menu item is a
configurable thing.  When two items have the same classname, they can
"replace" each other.  When they are differentiated, they open in
different tabs.

3.  When switching patients, you need the previous patient demographics,
form_encounter, history and other things to update and replace.  We
don't want someone thinking they are working in one patient's record to
actually be changing stuff for another patient!  This is a case where it
is a total top level reload of CERTAIN tabs, but not a total reset of
everything currently open.

-Suggestion:  Create a mechanism for allowing the user to configure the
default tabs, as well as the name/target variables in the menu json
configuration to set a menu item as either Unique (one at a time only)
or allow multiple copies of the same item.

**Comment by mhn94** [comment]
So for point 1, are you saying that this issue may not be an issue for some cases/we may want duplicate tabs open in some cases?

I recognized the behavior you described in point 2. I originally thought it was an issue and the target names were supposed to be unique. However, after looking at the menu_data.json file, I realized that this wasn't the case and concluded that it wasn't an issue, since it seemed like tabs were grouped together by similarity in function. Should they be unique?

For point 3, I'll look into this and make sure it's working properly.

Thank you for your input!

**Comment by mhn94** [comment]
After thinking about this some more, I think determining the qualifications for which tabs can have duplicates open can be tricky. The one qualification that makes sense is having a search feature, which would be the majority of the tabs. Everything else seems like a matter of opinion.

**Comment by mhn94** [comment]
I should mention that I have noticed that when switching patients, the previous patient's demographics doesn't update and replace in all modules. I didn't submit that solution in the above PR. I felt as if that was a separate but connected issue. So I have submitted a PR that fixes the original issue, until we have further discussed the points that were made here. And I will be working on creating a solution that fixes point 3.

Please let me know how to proceed, if I'm approaching this wrong.

Also, I'm SO SORRY for all of the notifications regarding this issue!

**Comment by mhn94** [comment]
Solved w/ PR [1535](https://github.com/LibreHealthIO/lh-ehr/pull/1535)
