### ISSUE TITLE
The “Submit” Button in Patient List Report functions like the “Export To CSV” button 

### ISSUE THREAD

**Issue by yamamashakaa** [LibreHealthIO/lh-ehr#1537]
A) Outreachy Username: Yamama 
B) Issue title: The “Submit” Button in Patient List Report functions like the “Export To CSV” button 
C) Report Date: 10/30/2019
D) Sites Affected: Documentatio¬¬n Site 
E) OS/ browser used: Firefox and chrome browser on Windows10 OS  
F) EHR Workflow module: When I wanted a patient list for specific provider.
G) Steps to Reproduce the Issue: 
1) login to your account
2) Click on “Reports” item which is the 9th  item in the top menu.
3) Choose “Clients” and then “Patient  list” from the drop down menu. 
4) Choose the provider you want to check their patients list.
5)Click “Submit”.
6) Results appear (Patient list).
7)  Click “Export To CSV”  button.
8)A pop up to Save the CSV file. 
9) Change the searching/filtering criteria.
10)Click Submit again
11)A pop up that asks you to save CSV file appear again ( The submit button don’t submit, it functions like the Export to CSV button)
Note : The same things happen weather accept to save the CSV file or not 
![image](https://user-images.githubusercontent.com/16443315/68046202-fa61cd00-fce3-11e9-8a69-eaba4feb54a4.png)
H)Expected Behavior: When I changed the provider name  and click submit I expected to get the patients list for the provider I chose .
I) What Actually Happened: a popup to save the CSV files appear.
J) Screenshots with Explanation:  
The following image shows what happened when clicking submit button after Exporting   CSV once before.
![image](https://user-images.githubusercontent.com/16443315/68046213-0483cb80-fce4-11e9-9e04-4c1d5881b47b.png)
K) Estimation of Severity:  Major: module function continues with workaround 
M) Solution: Set the value to false in Patient_list.php and add or condition in the if statement
(I tested it and it works fine without causing any conflict)
![image](https://user-images.githubusercontent.com/16443315/68046246-17969b80-fce4-11e9-9aec-12f55f83b2c7.png)

**Comment by Ngai-E** [comment]
Yes @yamamashakaa this is a bug. Thank you. I will hop over and test your fix.

**Comment by mhn94** [comment]
Looks like this issue has already been solved and merged. Can it be closed, @Ngai-E and @muarachmann?

**Comment by muarachmann** [comment]
Hmmmm not sure about this ... can you reference?

**Comment by mhn94** [comment]
#1539

**Comment by muarachmann** [comment]
Thanks closing this
