### ISSUE TITLE
After setting up docker in my pc, i i typed http://localhost:8090/ in my browser, but i get the following errors below

### ISSUE THREAD

**Issue by OfficialOzioma** [LibreHealthIO/lh-ehr#1543]
ERROR: query failed: ALTER TABLE `tf_patients_tags` ADD KEY `pid_index` (`pid`)

Error: Table 'libreehr.tf_patients_tags' doesn't exist

/var/www/html/library/vendor/libreehr/Framework/Plugin/Migration/Migrate.php at 233:sqlStatement
/var/www/html/library/pluginsystem/PluginSystem.php at 140:upgradeFromDirective(-- -- Comment Meta Language Constructs: -- -- #IfNotTable -- argument: table_name -- behavior: if the table_name does not exist, the block will be executed -- #IfTable -- argument: table_name -- behavior: if the table_name does exist, the block will be executed -- #IfMissingColumn -- arguments: table_name colname -- behavior: if the colname in the table_name table does not exist, the block will be executed -- #IfNotColumnType -- arguments: table_name colname value -- behavior: If the table table_name does not have a column colname with a data type equal to value, then the block will be executed -- #IfNotRow -- arguments: table_name colname value -- behavior: If the table table_name does not have a row where colname = value, the block will be executed. -- #IfNotRow2D -- arguments: table_name colname value colname2 value2 -- behavior: If the table table_name does not have a row where colname = value AND colname2 = value2, the block will be executed. -- #IfNotRow3D -- arguments: table_name colname value colname2 value2 colname3 value3 -- behavior: If the table table_name does not have a row where colname = value AND colname2 = value2 AND colname3 = value3, the block will be executed. -- #IfNotRow4D -- arguments: table_name colname value colname2 value2 colname3 value3 colname4 value4 -- behavior: If the table table_name does not have a row where colname = value AND colname2 = value2 AND colname3 = value3 AND colname4 = value4, the block will be executed. -- #IfNotRow2Dx2 -- desc: This is a very specialized function to allow adding items to the list_options table to avoid both redundant option_id and title in each element. -- arguments: table_name colname value colname2 value2 colname3 value3 -- behavior: The block will be executed if both statements below are true: -- 1) The table table_name does not have a row where colname = value AND colname2 = value2. -- 2) The table table_name does not have a row where colname = value AND colname3 = value3. -- #IfNotIndex -- desc: This function will allow adding of indexes/keys. -- arguments: table_name colname -- behavior: If the index does not exist, it will be created -- #EndIf -- all blocks are terminated with and #EndIf statement. -- -- Indexes for table `tf_patients_tags` -- ALTER TABLE `tf_patients_tags` ADD KEY `pid_index` (`pid`); )
/var/www/html/library/pluginsystem/PluginSystem.php at 94:migrate(/var/www/html/interface/tags_filters/migrations)
/var/www/html/library/pluginsystem/PluginSystem.php at 56:init()
/var/www/html/library/pluginsystem/PS.php at 14:getInstance()
/var/www/html/library/pluginsystem/bootstrap.php at 26:init()
/var/www/html/interface/globals.php at 542:include_once(/var/www/html/library/pluginsystem/bootstrap.php)
/var/www/html/interface/login/login.php at 33:include_once(/var/www/html/interface/globals.php)

**Comment by OfficialOzioma** [comment]
@Ngai-E can you help me here

**Comment by Ngai-E** [comment]
My guess is you are trying to install Librehealth EHR right? You do not need docker to install that. Please confirm what you want to accomplish.

**Comment by OfficialOzioma** [comment]
**@Ngai-E** yes am trying to install **Librehealth EHR**, and i using docker, which is the best way to install it on my Local Pc

**Comment by muarachmann** [comment]
Okay ... @OfficialOzioma this looks weird, try cleaning your db and starting afresh, also try to run sql_upgrade script before running the setup. Alternatively you can follow the docs here https://github.com/LibreHealthIO/lh-ehr/blob/master/INSTALL.md

**Comment by robbyoconnor** [comment]
I think I know what caused this -- I tried to make it easy to get started -- but I should add "run sql_upgrade" after set up to the docs.

**Comment by muarachmann** [comment]
Exactly!
