### ISSUE TITLE
Missing Form Items in Lab Overview

### ISSUE THREAD

**Issue by mhn94** [LibreHealthIO/lh-ehr#1553]
A) **Outreachy Username:** maggie.negm
B) **Issue Title:** Missing Form Items in Lab Overview
C) **Report Date:** 2/10/2020
D) **Sites Affected:** Docs Site
E) **OS/Browser Used:** Chrome browser in Linux OS
F) **EHR Workflow Module:** Lab Overview
G) **Steps to Reproduce the Issue:**

1. Select a patient by opening a patient profile. (One way to do this is by using the “Patient Finder” tool.)
2. Select “Procedures” from the main menu.
3. Select “Lab Overview” under “Procedures.”
4. Under the “Select items” heading, there should be a check list of LOINC Codes.
5. Check the console for error messages.

H) **Expected Behavior:** The form should load with the checklist, and no critical errors should show in the console.
I) **What Actually Happened:** No checklist form is displayed when the module loads, so users cannot choose input to submit. Although, users can select the “Submit” button, but it will always return the results “No parameters selected.” There are also 404 error messages in the console.
J) **Screenshots with Explanation:**
The form within the “Lab Overview” module in the Docs server looks like this: 
![lab-overview-issue-view](https://user-images.githubusercontent.com/8771586/74401567-a9d43280-4def-11ea-82c2-bbf6111c9373.png)

This issue doesn't exist in the NHANES server, where it looks like this:
![lab-overview-how-it-should-look](https://user-images.githubusercontent.com/8771586/74401581-b5275e00-4def-11ea-8275-cc0ae67c65ba.png)

The following are the error messages that are displayed in Chrome Inspector when the module is loaded on the Docs server:
![console-errors](https://user-images.githubusercontent.com/8771586/74401591-be182f80-4def-11ea-9343-12512bc0e97a.png)

K) **Estimation of Severity:** Critical – module function continues with ongoing errors
M) **Solution:** Find the missing resources, then change the URL links within the code.

**Comment by xurror** [comment]
@mhn94, I sent a PR for this. I have rectified the console errors but I lack dummy data for functiona; review. Please can you review?
https://github.com/LibreHealthIO/lh-ehr/pull/1574
