### ISSUE TITLE
Missing Form Labels in Report Forms

### ISSUE THREAD

**Issue by mhn94** [LibreHealthIO/lh-ehr#1556]
A) **Outreachy Username:** maggie.negm
B) **Issue Title:** Missing Form Labels in Report Forms
C) **Report Date:** 2/26/2020
D) **Sites Affected:** Docs Site, NHANES
E) **OS/Browser Used:** Chrome browser in Linux OS
F) **EHR Workflow Module:** Report – Services by Category, Report – Cash Receipts by Provider, Report – Receipts Summary, Report – Collections
G) **Steps to Reproduce the Issue:**

1. Go to each module.
    • Report – Services by Category: Reports > Visits > Services by Category
    • Report – Cash Receipts by Provider: Reports > Financial >  Cash Receipts by Provider
    • Report – Receipts Summary: Reports > Financial >  Receipts Summary
    • Report – Collections: Reports > Financial >  Collections
2. View form.

H) **Expected Behavior:** Each form item should have a label next to it to make its function clear to the user.
I) **What Actually Happened:** Some form items do not have labels next to them and can confuse users.
J) **Screenshots with Explanation:**
Ex. The image below shows the “Cash Receipts by Provider” report module with a form item that has no label next to it.
![CashReceipts-missing-label](https://user-images.githubusercontent.com/8771586/75612929-36703780-5af6-11ea-8c16-caae212d8f02.png)

The following image shows the code of the form within the “Cash Receipts by Provider” module from the Chrome Inspector:
![form-chrome-inspector-w-outline](https://user-images.githubusercontent.com/8771586/75612965-84853b00-5af6-11ea-9c6c-0c229dfb088d.png)

K) **Estimation of Severity:** Minor – distracting or confusing but workflow can continue correctly
M) **Solution:**
Add labels next to the form items:
    • Report – Services by Category: Add the label “Code Category” next to drop-down list that starts with “All.”
    • Report – Cash Receipts by Provider: Add the label “Sort By Date” next to the Payment Date/Invoice Date drop-down list.
    • Report – Receipts Summary: Add the label “Sort By Date” next to the Payment Date/Invoice Date drop-down list and the label “Facility” next to the “Facility” drop-down list.
    • Report – Collections: Add the label “Account Type” next to the drop-down list that starts with “Open.”

**Comment by xurror** [comment]
I'll like to work on this
