### ISSUE TITLE
Button to expand "Add Facility" modal disappears in Chrome

### ISSUE THREAD

**Issue by d3n23z** [LibreHealthIO/lh-ehr#1561]
**A) Outreachy Username:** d3n23z
**B) Issue title:** Button to expand "Add Facility" modal disappears in Chrome
**C) Report Date:** March 5, 2020
**D) Sites Affected:** Documentation Site, NHANES
**E) OS/browser used:** Chrome on OS X
**G) Steps to Reproduce the Issue:**

1. Go to the Documentation Site or NHANES in Chrome.
2. Hover over "Administration" in the menu and click to open the "Facilities" tab.
3. Click the button to add a new Facility.
4. If you see the "fullscreen"/expand button, reduce the tab width or browser width until it disappears. This issue occurs when the tab width is lower than a certain number of px.

**H) Expected Behavior:** The button should be visible and usable.
**I) What Actually Happened:** The button disappears.
**J) Screenshots with Explanation:**
![screenshot](https://user-images.githubusercontent.com/61851433/76039192-84bf7500-5f00-11ea-88ce-8b699b1360dc.png)

![screenshot](https://user-images.githubusercontent.com/61851433/76039217-986adb80-5f00-11ea-9d73-1b002b257347.png)

It appears that the button is being hidden using JavaScript (and that this could be intentional). The button appears in Firefox. 

**K) Estimation of Severity:** Trivial. The form is still usable, although the container is very small making using it a bit difficult.

**Comment by Ngai-E** [comment]
please fix and test for other browsers.

**Comment by muarachmann** [comment]
Hi @i8ag7z , @Ngai-E I am on chrome OS X and can't seem to reproduce this bug .. here is my screen

Maybe more details about screensize etc may be useful here
<img width="1280" alt="Screen Shot 2020-03-09 at 2 46 36 AM" src="https://user-images.githubusercontent.com/16350814/76176263-39cb8900-61b0-11ea-80f0-e1e6ca33ca09.png">

**Comment by i8ag7z** [comment]
This does seem to have something to do with the tab width. When I set the modal width (iziModal settings in facilities.php) to a number much lower than the current one (700) the button appears at lower widths, but unfortunately that makes the modal too small.

**Comment by Ngai-E** [comment]
Yeah me too. But he insisted.
