### ISSUE TITLE
 Patience Insurance poping up without being clicked.

### ISSUE THREAD

**Issue by ahanipeitra1994** [LibreHealthIO/lh-ehr#1565]
A) Outreachy  Username : Peitra.
B) Issue Title: Patience Insurance popping up without being clicked.
C)  Report Date:  03/14/2020.
D) Sites Affected: Local  Instance,
E)  OS/browser used:  windows10/ Mozilla FireFox.
F)  EHR Work Flow Module: Patience/client-> Finder->Edit(Demographics).
G)  Steps to Reproduce the Issue:
1)	Click on  “Patient/Client “ on the main menu.
2)	Click on “ Finder” .
3)	Click on “ Patient Name” .
4)	Click on “ Edit (Demographics)”.
H)  Expected Behavior: The Insurance should not appear because it has not been clicked .
I)  What Actually Happened: When the Edit( Demographics) is Clicked, the Patients insurance appears in a second.which was not Clicked.
 J)  Screenshot With Explanation. It is difficult to get a screenshot because the  Insurance appears in  a second. 
![image](https://user-images.githubusercontent.com/60817596/76683161-2aaa6800-6602-11ea-8a07-586be1e70b4c.png)

  

K)  Estimation of Severity: Minor distraction or confusing but workflow can continue correctly.
L)  Solution: The codes are wrongly written and can be corrected using  Java Script.

**Comment by robbyoconnor** [comment]
Did you discuss this before posting?

**Comment by robbyoconnor** [comment]
Also as reported this issue is actually not useful
