### ISSUE TITLE
remove underscore in section add "medical problem"

### ISSUE THREAD

**Issue by xurror** [LibreHealthIO/lh-ehr#1568]
Steps to Reproduce the Issue:

1. Go to a patient profile.
2. using Patient Finder (“Patient/Client” from the main menu > “Finder” under “Patient/Client”) and choose a patient.
3. Select “Issues” under the patient’s name.
4. Create any issue by clicking the “Add" next to "medical problem"
The title of the modal contains an underscore

**Comment by AsaoluElijah** [comment]
Hi @xurror can i work on this?

**Comment by xurror** [comment]
Suit yourself

**Comment by MathurinNkenfack** [comment]
Hi @xurror  solved the problem, should I do a pull request?
