### ISSUE TITLE
Clicking on "Search or Add Patient" form labels do not highlight input fields

### ISSUE THREAD

**Issue by d3n23z** [LibreHealthIO/lh-ehr#1578]
**A) Outreachy Username:** d3n23z
**B) Issue Title:** Clicking on "Search or Add Patient" form labels do not highlight input fields
**C) Report date:** 3/17/2020
**D) Sites Affected:** Local instance
**E) OS/browser used:** Firefox on OS X
**F) EHR Workflow Module:** Search or Add Patient
**G) Steps to Reproduce the Issue:**

1. Open the “Search or Add Patient” module (Patient/Client -> Add New/Search).
2. Navigate to the “Face Sheet” form directly under the “Search or Add Patient” heading.
3. Click on what should be a label for the form (such as “NAME:”).

**H) Expected Behavior:** Clicking a label should highlight the corresponding input field.
**I) What Actually Happened:** Clicking the text does not highlight the corresponding input field. 
**J) Screenshots with Explanation:**
![screenshot](https://user-images.githubusercontent.com/61851433/77096635-d7069880-69cc-11ea-8d3e-3883c3e585a9.png)
Clicking on any of the labels does not highlight the corresponding input field.

![screenshot](https://user-images.githubusercontent.com/61851433/77096605-cbb36d00-69cc-11ea-8ed3-f8930d3925a2.png)
As you can see there is no label tag.

**K) Estimation of Severity:** Trivial. The form is still usable. 
**M) Solution:** Add label tags for the form inputs.

**Comment by Ngai-E** [comment]
For consistency with the rest of the forms in the EHR, we intend on ignoring this for now. Thanks anyway.
