### ISSUE TITLE
Error in docker setup

### ISSUE THREAD

**Issue by uwaiszaki** [LibreHealthIO/lh-ehr#1589]
I am getting this error while running localhost:8000
![gs1](https://user-images.githubusercontent.com/32809190/77427723-e0449a80-6dfc-11ea-853b-0a965ff26def.png)
![gs2](https://user-images.githubusercontent.com/32809190/77427742-e89cd580-6dfc-11ea-84c4-591fbdd15c9c.png)

**Comment by uwaiszaki** [comment]
@robbyoconnor Can you please help me solve this error.

**Comment by robbyoconnor** [comment]
You're probably running MySQL locally. I've tested this extensively. Be sure to uninstall or stop all instances on your system. This isn't a bug.
