### ISSUE TITLE
Missing Navbar in Administrator dashboard

### ISSUE THREAD

**Issue by anitakay** [LibreHealthIO/lh-ehr#1607]
A) Outreachy Username: kithama
B) Issue title: Missing Navbar Menu for New Administrator dashboard
C) Report Date: 04/06/ 2020
D) Sites Affected: Local Instance
E) OS/ browser used: Mozilla Firefox
F) EHR Workflow module: Administrator Dashboard
G) Steps to Reproduce the Issue:
•	Login into the default Administrator’s  Dashboard (The one created during installation).
•	Create a new User account with Administrative privileges.
•	Logout from the default Administrator dashboard.
•	Login to the newly created administrator accounts.
•	The Administrator dashboard has no Navbar Menu
H) Expected Behavior: In the Administrator dashboard, the Navbar Menu should be present with administrative privileges.
I) What Actually Happened: On opening the Administrator dashboard, the dashboard appears with the navbar having only “logout” link. It doesn’t even show the Full names of the user.
J) Screenshots with Explanation: As shown below, upon an administrator login, the dashboard has logout option.
 
![image](https://user-images.githubusercontent.com/50633277/78662030-65897e00-78d8-11ea-9b94-bca3e7d6ff01.png)

Estimation of Severity: Major. No functionality is available for the Administartor.
L) Workaround: NA
M) Solution: Adding the missing navbar code to the  Administrator dashboard.
 
![image](https://user-images.githubusercontent.com/50633277/78662132-8f42a500-78d8-11ea-9b98-4fc200de9ba6.png)

**Comment by Paras2Bhardwaj** [comment]
i want to solve this issue

**Comment by anitakay** [comment]
The issue was resolved
