### ISSUE TITLE
Calendar End Date And Start Date Display Any Date Entry 

### ISSUE THREAD

**Issue by ahanipeitra1994** [LibreHealthIO/lh-ehr#1630]
A) **Outreachy  User Name:** Peitra
B) **Issue Title**: The Calendar End Date And Start Date Display Wrongly
C)  **Report Date:**  07/29/2020
D) **Sites Affected**: Local Instance
E)  **OS/browser used**: Windows 10/Mozilla FireFox /chrome
F)  **EHR Work Flow Module:** Calendar
G)  **Steps to Reproduce the Issue:**
1)	Click on “Calendar” on the navigation bar if it is not already open by default
2)	 Click on “ Add” on the calendar tab 
3)	A popup will open which displays the "start date" and the "end date"
4)	Enter different dates on both the start date and end date, but make sure the end date is earlier than the start date. Then click the submit button

H)  **Expected Behavior:** I expected to see a popup or a sign showing that the end date cannot be earlier or before the start date.
I)  **What Actually Happened:**  When I enter an end date earlier than the start date, It submits without an error message.
 J)  **Screen With Explanation**. From the screenshot below the dates are displayed
![image](https://user-images.githubusercontent.com/60817596/88857555-6b400200-d1ee-11ea-925c-5d7a84793766.png)

![image](https://user-images.githubusercontent.com/60817596/88857356-0c7a8880-d1ee-11ea-9367-d9c08969e31b.png)

 
 

  

K)  **Estimation of Severity**: Major  module function continues with work around.
L) **Solution:** An if/ else statement is needed to make sure a user is notified if the date entry is not correct.

**Comment by ayush0x00** [comment]
@muarachmann kindly close this issue as it has already been fixed. There are a few more issues which are open despite being fixed. This just increases the number of open issues to work on.
