### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Roushangopal** [LibreHealthIO/lh-ehr#1642]
![Screenshot from 2020-08-20 11-30-46](https://user-images.githubusercontent.com/55797406/90722800-24b76200-e2d9-11ea-993f-414df4aa9a97.png)
While installing the website on the local server it shows errors while setting it up,please help me

**Comment by muarachmann** [comment]
Please turn error reporting off as stated on the readme also what version of PHP are you on. Currenly 7.2 is a good to go. 7.4 has some backward compatibility issues. Let me know if you have any other worries

**Comment by ayush0x00** [comment]
The step 3 completion is taking much longer time (It is in this step since last 15 min). No error is being thrown. Is it normal?

![Screenshot from 2020-11-20 00-26-29](https://user-images.githubusercontent.com/44584229/99710917-24408a00-2ac7-11eb-975a-5bf0429200e7.png)
