### ISSUE TITLE
Non-uniform Spacing 

### ISSUE THREAD

**Issue by RiyaJ2311** [LibreHealthIO/lh-ehr#1650]
On the homepage of [Librehealth](https://librehealth.io/), the slider is non-uniform.
![image](https://user-images.githubusercontent.com/48223671/109097882-3c6b1980-7746-11eb-8266-0dd7c30a12c7.png)
![image](https://user-images.githubusercontent.com/48223671/109097904-47be4500-7746-11eb-8106-1568aae9ffe9.png)

**Why is it important?**
Nonuniformity issues can hamper the design and review processes, caused by brightness or color differences at different parts of the screen. Potential misjudgment in design can cause the final output to differ from what’s presented, severely affecting the quality of a design. The solution lies in the [law of uniform connectedness](https://lawsofux.com/law-of-uniform-connectedness/). This Law deals with a “grouping effect”: users tend to perceive elements as connected to each other thanks to colors, lines, frames, or other shapes. In this case, the frame is not equal so the suggestion is to create a uniform frame size.

**Who will benefit from this?**
1. Users as this evokes unpleasing nature which might irritate the user

**Comment by muarachmann** [comment]
Please feel free to report here - https://gitlab.com/librehealth/lsc/librehealth.io
