### ISSUE TITLE
WINDOWS_INSTALL.md need to update

### ISSUE THREAD

**Issue by iamsuyashpatel07** [LibreHealthIO/lh-ehr#1658]
1)
 ## below 2 colored lines are removed from php configuration setting
<img width="629" alt="Depracated" src="https://user-images.githubusercontent.com/59373438/123887086-79525180-d96e-11eb-9c05-9dc76854c545.png">

2) ##step_4.png need to update because there are certain changes You can differentiate with there images.
#Old
![Step_4](https://user-images.githubusercontent.com/59373438/123887962-18c41400-d970-11eb-92ed-75e54f74b2fc.png)
#New
<img width="799" alt="Step_4" src="https://user-images.githubusercontent.com/59373438/123887622-773cc280-d96f-11eb-8256-70eb0d2461a7.png">

**Comment by iamsuyashpatel07** [comment]
let me Know, show that I can fix it.

**Comment by muarachmann** [comment]
@iamsuyashpatel07 I still don't get what the issue might be? any errors encountered?

**Comment by iamsuyashpatel07** [comment]
@aethelwulffe Yes you're right actually problem was from side.
