### ISSUE TITLE
LH-EHR: Patient/Client tab

### ISSUE THREAD

**Issue by SharonA10** [LibreHealthIO/lh-ehr#1676]
When searching for a patient under the Patient/Client tab, the New Encounter and Past Encounter List box moves on the screen.

Steps to replicate the issue:
1. Log onto the LibreHealth application
2. Click on the "Patient/Client" tab
3. This will open up the patient demographic page
4. Click on any patient name
5. This will open up the selected patient's face sheet
6. To the top right corner, there will be box that contains details about the New Encounter and Past Encounter List
7. When we scroll up/down the screen the box keeps moving. Sometimes it also freezes and stays on the application screen.

![image](https://user-images.githubusercontent.com/114970450/193880326-3df0fed9-fd02-4b62-a79b-badcf3f31125.png)

![image](https://user-images.githubusercontent.com/114970450/193879725-46a78ca1-bc62-4a15-a7d6-fed4b6785732.png)

**Comment by sunbiz** [comment]
Fixed in https://github.com/LibreHealthIO/lh-ehr/commit/537cfc64a9902fb5147ad832b38e3877af5c45a3
