### ISSUE TITLE
Setup Script (web version) improvement

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/lh-ehr#191]
The setup script needs general improvement.  Some recent stuff from Matrix on openemr might be good, but we also need to make sure that it does not update the sqlconf.php file as "Installed" until AFTER it's actually successful.

Also need to make sure that SQL errors during setup are trapped and not silently skipped over to be found sometime later by the user when they try and use a part of the install.

**Comment by aethelwulffe** [comment]
Should add this to 1.0.1

**Comment by tmccormi** [comment]
More #91  related issues

**Comment by tmccormi** [comment]
The setup script should generate the sqlconf.php so there is no need to store a "template" copy of it.

This would be a good

**Comment by tmccormi** [comment]
Would be very useful if it checked the OS / PHP dependencies prior to starting the setup, like it does for the permissions.

**Comment by aethelwulffe** [comment]
This issue is covered elsewhere...abundantly.
