### ISSUE TITLE
Ability to pull "system / cloud / other" Status into an alert

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/lh-ehr#239]
As a vendor we sometimes urgently need to notify all my users that something is up, maintenance windows, new crop network etc.

Would like a common way to post notifications that can be retrieved and popup as alerts on the EHR side of life.

Obviously would only work where the EHR has access to the internet in some fashion.   But even something like a twitter feed api call would do it.

**Comment by aethelwulffe** [comment]
Several options would be nice, but a vendor-specific communication protocol with customers sounds like a general practical approach.  Being able to touch general social media seems like something that might get mis-used.  Not disagreeing with the concept, just that appropriate warnings and restrictions be put on the can label.  "The Surgeon General has determined that this can send you to jail" or something like that.
  When I look at DIRECT and all that, I am not seeing something that is really in the vein of what you are talking about, but what is the possibility of a central LibreHealth alert system for security etc...?  I would like to see the Client-to-Project communication tool get stood up first.  Just going with Twitter or any other single social media tool seems incomplete.  It is a case of more-the-merrier.

**Comment by tmccormi** [comment]
Twitter is just a common model for system announcements these days.

**Comment by tmccormi** [comment]
Slack channel chatbot and RocketChat channels are also a option.

**Comment by aethelwulffe** [comment]
Honestly, I don't see us being able to pull off a vendor application use case in our project.  RocketChat, sure..but really for simple "I am destroying the server" messages, would not a native thing that just uses email do a rather lot?
#1154
