### ISSUE TITLE
Changes to the hcfa print and x12 files for Taxonomy codes

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#268]
I will commit this in the near future

**Comment by aethelwulffe** [comment]
Thang-Kew!

**Comment by teryhill** [comment]
Now for a more detailed description. This commit puts the provider Taxonomy code in 24I and 33B along with the referrer's Taxonomy code in box 17a

It also adds the provider taxonomy in the 2310b loop and in the 2000A loop
