### ISSUE TITLE
Changes for Misc Billing form to handle needed items

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#269]
I will be committing this in the near future

**Comment by aethelwulffe** [comment]
I am absolutely positive that I will need your assistance when diving into the interactive 1500 again.  To lighten the load, we can make sure it satisfies the current specific needs of your LSS customers.  I am pretty sure that if it satisfies Florida and NC medicaid, we will be catching most every issue possible.

**Comment by aethelwulffe** [comment]
None of which sounds like I can get back to this week...

**Comment by teryhill** [comment]
We may need to just talk it out a couple of times. That should let us develop an attack plan

**Comment by teryhill** [comment]
This is actually the code that is currently being run on LSS 4.2.1 and 4.2.2
