### ISSUE TITLE
generate_id() and GenID() 

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/lh-ehr#290]
Need to look at the adodb generate_id and genID functions dealing with sessions and ID's for insurance_companies, addresses, x12_partners and some other areas.
Related code can be found in the templates directory as well as sql.inc, controller.php linked Controller.class.php.
These functions call an adodb function to generate a very goofy ID that is being used as the key in the above listed tables.
I see no reason to utilize it for that purpose.  It also causes issues with current versions of the server environment, and there appear to be numerous hacks to circumvent that issue.
The ID's of those tables are not set to autoincrement, and are set to DEFAULT=0.

**Comment by aethelwulffe** [comment]
Also review the use of the documents tables and the "sequences" table...a table with a single field in it.

**Comment by aethelwulffe** [comment]
The GenID stuff still chaps my rear.  Any suggestions @pri2si17-1997

**Comment by pri2si17-1997** [comment]
@aethelwulffe I have this issue in my mind. But since I'm refactoring database, I can't work on queries. But I will update you soon.

**Comment by aethelwulffe** [comment]
Just wanting to make sure this doesn't get lost in the shuffle, because 
it is an ugly legacy thingie.

**Comment by pri2si17-1997** [comment]
No no.. I remember what I have to do. But as I told, I haven't expected this database refactoring to take so much time. I will try to get this refactoring done soon.
