### ISSUE TITLE
Mods to Globals order of operation

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/lh-ehr#361]
Globals don't behave the way I thought.I thought that the initialization process worked to first get defaults from the globals array and then look in the database. That way you wouldn't need to save globals to get the defaults of globals that are newly added. But you have to go and save them in order to take effect. 

So what I was seeing was what happens when there's no global for default screens set. What do you think about enhancing globals so that the user doesn't have to go to edit-globals and save for newly added globals to be set?  --Ken

**Comment by teryhill** [comment]
the global default should be added to /interface/globals.php in the section starting about line 343

**Comment by aethelwulffe** [comment]
What is the status of this issue?  We have a commit here, but I am not sure if that is the whole issue.

**Comment by aethelwulffe** [comment]
Can we get a better definition of what this issue is to address (as a specification for a work ticket)?
