### ISSUE TITLE
Audit features for appointments.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#529]
The request from the user is to see the users that have touched the appointments, They want to know who rescheduled an appointment and when. They want this information to be accessed from the demographics screen.

I have added the original user(person who created the appointment) and the users who changed the status  to the Patient Flow Board report .

**Comment by teryhill** [comment]
Past appointments are changed to reflect the moved appointment's

![image](https://cloud.githubusercontent.com/assets/4655366/24432768/4b76a306-13f2-11e7-980c-a711edd62e34.png)

**Comment by teryhill** [comment]
The name associated with the past appointment is the person that originally scheduled the appointment. I am not getting the results that I want with out changing the files to help with this.

I am leaning towards the Idea of making a new section for appointment tracking.

Any Ideas on ways to do this are welcome.

**Comment by aethelwulffe** [comment]
You could just have a [modified] or [changes] show up, then hovertext 
gives the details.  you could provide a lot of text that way, without 
making anything goofy in the history listing.

**Comment by teryhill** [comment]
@azwreith Any Ideas on how to accomplish this? The patient tracker element file stores the information.

**Comment by teryhill** [comment]
Adding this her since it is where it belongs.

![image](https://user-images.githubusercontent.com/4655366/33639416-2b4e35a8-d9f9-11e7-8db6-858d662adfba.png)
