### ISSUE TITLE
Bronchitis Form

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/lh-ehr#625]
I wanted to use this template as part of the user guide but I noted that the coding mechanism codes by ICD-9 and not ICD-10. I have no idea how difficult it would be to have both as we see throughout most of the EHR

**Comment by rehoyt** [comment]
I attempted to create my own form using the layout based forms, but gave up. Not user friendly or intuitive

**Comment by tmccormi** [comment]
It's definitely something that requires an "expert" at using the layout tool.

**Comment by aethelwulffe** [comment]
All references to ICD or any specific code publication need to be removed.  Instead, a check should be made against the code_types table where there is a need to see if a code is a Dx, Tx, Vx, etc...
