### ISSUE TITLE
BYTEBUG LOG

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/lh-ehr#695]
The following are a list of php notices from the logs that should be attended to.  Mostly, they involve things directly related to using uninitialized arrays before there is any user input.

From the vast wisdom of the PHP Manual:

    Relying on the default value of an uninitialized variable is problematic in the case of including one file into another which uses the same variable name. It is also a major security risk with register_globals turned on. E_NOTICE level error is issued in case of working with uninitialized variables, however not in the case of appending elements to the uninitialized array. isset() language construct can be used to detect if a variable has been already initialized. Additionally and more ideal is the solution of empty() since it does not generate a warning or error message if the variable is not initialized.

- [ ]  PHP Notice:  Array to string conversion in C:\\xampp\\htdocs\\libremaster\\gacl\\gacl_api.class.php on line 1077
- [ ]  PHP Notice:  Only variables should be assigned by reference in C:\\xampp\\htdocs\\libremaster\\gacl\\gacl_api.class.php on line 1089
- [ ]  PHP Notice:  Only variables should be passed by reference in C:\\xampp\\htdocs\\libremaster\\interface\\patient_file\\summary\\demographics.php on line 1686
- [ ]  PHP Notice:  Only variables should be passed by reference in C:\\xampp\\htdocs\\libremaster\\library\\adodb\\adodb-xmlschema.inc.php on line 268
- [ ]  PHP Notice:  Only variables should be passed by reference in C:\\xampp\\htdocs\\libremaster\\library\\globals.inc.php on line 3179
- [ ]  PHP Notice:  Trying to get property of non-object in C:\\xampp\\htdocs\\libremaster\\library\\sql.inc on line 254
- [ ]  PHP Notice:  Undefined index: Administration in C:\\xampp\\htdocs\\libremaster\\interface\\tags_filters\\start.php on line 68
- [ ]  PHP Notice:  Undefined index: authorizeduser in C:\\xampp\\htdocs\\libremaster\\modules\\calendar\\index.php on line 39
- [ ]  PHP Notice:  Undefined index: clone_database in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 29
- [ ]  PHP Notice:  Undefined index: collate in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 26
- [ ]  PHP Notice:  Undefined index: data_type in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 153
- [ ]  PHP Notice:  Undefined index: datacols in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 180
- [ ]  PHP Notice:  Undefined index: dbname in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 25
- [ ]  PHP Notice:  Undefined index: default in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 185
- [ ]  PHP Notice:  Undefined index: desc in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 186
- [ ]  PHP Notice:  Undefined index: development_translations in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 31
- [ ]  PHP Notice:  Undefined index: edit_options in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 184
- [ ]  PHP Notice:  Undefined index: form_save in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_globals.php on line 122
- [ ]  PHP Notice:  Undefined index: formaction in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 147
- [ ]  PHP Notice:  Undefined index: igroup in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 17
- [ ]  PHP Notice:  Undefined index: inst in C:\\xampp\\htdocs\\libremaster\\setup.php on line 169
- [ ]  PHP Notice:  Undefined index: iufname in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 16
- [ ]  PHP Notice:  Undefined index: iuname in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 15
- [ ]  PHP Notice:  Undefined index: iuser in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 13
- [ ]  PHP Notice:  Undefined index: iuserpass in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 14
- [ ]  PHP Notice:  Undefined index: lengthHeight in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 177
- [ ]  PHP Notice:  Undefined index: lengthWidth in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 176
- [ ]  PHP Notice:  Undefined index: list_backup_id in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 183
- [ ]  PHP Notice:  Undefined index: list_backup_id in C:\\xampp\\htdocs\\libremaster\\library\\options.inc.php on line 1733
- [ ]  PHP Notice:  Undefined index: list_id in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 182
- [ ]  PHP Notice:  Undefined index: login in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 23
- [ ]  PHP Notice:  Undefined index: loginhost in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 19
- [ ]  PHP Notice:  Undefined index: maxSize in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 178
- [ ]  PHP Notice:  Undefined index: mode in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_globals.php on line 264
- [ ]  PHP Notice:  Undefined index: mode in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_globals.php on line 354
- [ ]  PHP Notice:  Undefined index: mode in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_globals.php on line 39
- [ ]  PHP Notice:  Undefined index: mode in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_globals.php on line 648
- [ ]  PHP Notice:  Undefined index: mode in C:\\xampp\\htdocs\\libremaster\\interface\\usergroup\\user_admin.php on line 47
- [ ]  PHP Notice:  Undefined index: no_root_db_access in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 30
- [ ]  PHP Notice:  Undefined index: pass in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 24
- [ ]  PHP Notice:  Undefined index: port in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 20
- [ ]  PHP Notice:  Undefined index: report_itemizing_temp_flag_and_id in C:\\xampp\\htdocs\\libremaster\\library\\clinical_rules.php on line 774
- [ ]  PHP Notice:  Undefined index: root in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 21
- [ ]  PHP Notice:  Undefined index: rootpass in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 22
- [ ]  PHP Notice:  Undefined index: server in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 18
- [ ]  PHP Notice:  Undefined index: source_site_id in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Installer.class.php on line 28
- [ ]  PHP Notice:  Undefined index: sql_admin_tool_url in C:\\xampp\\htdocs\\libremaster\\interface\\main\\tabs\\menu\\menu_data.php on line 10
- [ ]  PHP Notice:  Undefined index: state in C:\\xampp\\htdocs\\libremaster\\setup.php on line 14
- [ ]  PHP Notice:  Undefined index: titlecols in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 179
- [ ]  PHP Notice:  Undefined offset: 4 in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_globals.php on line 334
- [ ]  PHP Notice:  Undefined variable: access_group in C:\\xampp\\htdocs\\libremaster\\interface\\usergroup\\usergroup_admin.php on line 38
- [ ]  PHP Notice:  Undefined variable: my_id in C:\\xampp\\htdocs\\libremaster\\interface\\usergroup\\facility_user_admin.php on line 144
- [ ]  PHP Notice:  Undefined variable: numcols in C:\\xampp\\htdocs\\libremaster\\interface\\patient_file\\summary\\demographics.php on line 1165
- [ ]  PHP Notice:  Undefined variable: res in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_layout.php on line 957
- [ ]  PHP Notice:  Undefined variable: top_choice in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_globals.php on line 504
- [ ]  PHP Notice:  Undefined variable: userMode in C:\\xampp\\htdocs\\libremaster\\interface\\super\\edit_globals.php on line 606
- [ ]  PHP Notice:  Use of undefined constant Controller - assumed 'Controller' in C:\\xampp\\htdocs\\libremaster\\library\\classes\\Controller.class.php on line 91

**Comment by supernour09** [comment]
@aethelwulffe  how can i get those logs , i am using wamp and checks all the logs file didn't get those

**Comment by aethelwulffe** [comment]
Hi @supernour09 
Well, these are pretty old logs!

We have had a lot of changes to a lot of stuff since then.

How about we close this issue, or modify it and start posting log errors (with sign-off checks) for what we have *right now* ?
Welcome aboard Nour!

-Art

**Comment by aethelwulffe** [comment]
-question:  What are your logging options in php.ini?
