### ISSUE TITLE
Duplicated library files (jQuery and stuff)

### ISSUE THREAD

**Issue by MigDinny** [LibreHealthIO/lh-ehr#781]
This is an issue related to this GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5004282745061376/ & https://gitlab.com/librehealth/gci/issues/45

Duplicated files:

- \library\js\jquery-[*] _(a lot of minified versions are present; not sure about jquery.js & jquery121.js & jquery.livequery101.js )_

- \library\js\jquery-ui-1.8.21 & jquery-ui-1.8.6 _(these two different minified versions of jQuery UI are present and duplicated; not sure about jquery-ui.js)_

- \library\js\jquery.treeview-1.3 & jquery.treeview-1.4.1 

There is one library, **jquery-calendar.js**, which has its styles (.css) on root folder (library). I think it should be located in css folder (library/css)

Didn't find any other occurrence so far.

**Comment by robbyoconnor** [comment]
Title your issue better so that it's easier to see what was duplicated

**Comment by MigDinny** [comment]
@robbyoconnor is it good now ?

**Comment by robbyoconnor** [comment]
yup
