### ISSUE TITLE
In the Calendar when a user clicks on the patient allow the demographics tab to open.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#791]
Currently in the calendar when you click on the time slot with a patient assigned to the slot the add_edit_event opens. What needs to happen in addition to this is when the user clicks on the actual name the patients demographics screen needs to open.

**Comment by teryhill** [comment]
Assigned to @migdinny

**Comment by teryhill** [comment]
![image](https://user-images.githubusercontent.com/4655366/33521925-e8ea2e6c-d7ad-11e7-8ab8-afe9586f0fb2.png)

open this screen

![image](https://user-images.githubusercontent.com/4655366/33521933-0c3ed3c2-d7ae-11e7-80e3-70fdb7b65701.png)

**Comment by teryhill** [comment]
The patient flow board currently does this. By clicking on the patient name.

![image](https://user-images.githubusercontent.com/4655366/33521955-97a4f3e2-d7ae-11e7-8972-75097cff4412.png)

**Comment by MigDinny** [comment]
@teryhill Tried a lot of solutions and none of them worked. Can't find the code that creates the row on the calendar and the function topatient() when called on the console is undefined. I can't reproduce the flowboard system on the calendar.

Waiting for you to enlighten me.

**Comment by teryhill** [comment]
@MigDinny the calendar supplies a json for the events from get_provider_events.php

**Comment by teryhill** [comment]
@azwreith this is what is being worked on
