### ISSUE TITLE
Theme Global Setting Not Working

### ISSUE THREAD

**Issue by yehster** [LibreHealthIO/lh-ehr#805]
To reproduce, login on the 
ehr.librehealth.io/?site=lssc
The "global setting" for theme is currently set to "light"  However, if you inspect the HTML, the included .css theme being applied is always "style_metal.css"

Tried changing the theme in globals to the other options, and it always still just applies "style_metal".

metal seemed to have been removed at some point, so I copied light back to metal just to make sure that something gets applied for now.

**Comment by teryhill** [comment]
@yehster I changes the theme to tan on my system and it changed, but I changed it to tan on the lssc system and it did not change. We will run it down and see why unless you already have figured it out.

**Comment by Trodrige** [comment]
Hi, @yehster I tried replicating this. The default for me was 'light' and 'style_light.css'. Changing the theme, I still see 'style_light.css'. I'm I missing something? @teryhill

**Comment by Trodrige** [comment]
Yup @teryhill, I have the same behaviour on my system.

**Comment by teryhill** [comment]
@Trodrige so it is working on yours? Do you have a recent copy of the code?

**Comment by Trodrige** [comment]
@teryhill I observed the same thing as you did. It works on my system, but not on the demo site. It's been a while I pulled the code.

**Comment by aethelwulffe** [comment]
Is this resolved?
My current complaint with globals is that it takes *forever* to update.  Anyone know what is going on there???

**Comment by teryhill** [comment]
I have not seen this issue happening any more. Closing this issue

**Comment by teryhill** [comment]
@aethelwulffe my globals takes about 7 sec from the time I click save until it shows "Settings Saved"
