### ISSUE TITLE
Ideas: Discussion on changing the reports .

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#818]
I would like to see a project that would take the reports in the system and pull out the common functions and code in to files that can be re-used. most every report has a date range those could be made in to a function and placed in a common file. We could separate the HTML from the PHP code and get a number of reusable snippets thus reducing the complexity of the reports. This approach can and should be used on all the files in the system.

THIS WILL BE AN AFTER GCI PROJECT

**Comment by Trodrige** [comment]
I see, No "re-inventing the wheel". I'll start looking into the reports, see how we can tackle this.

**Comment by SoumyadeepJana** [comment]
@teryhill I didn't quite understand the report thing.Can you please explain a bit more?

**Comment by teryhill** [comment]
@SoumyadeepJana we should be able to make a set of function for the reports in a single file so that they can be called. It would help keep all the ways of doing things the same  ex if we had one function for choosing a provider, one function for choosing the facility.... This would condense the code.

**Comment by SoumyadeepJana** [comment]
@teryhill  This would save from writing redundant code, seems cool, count me in.

**Comment by teryhill** [comment]
@SoumyadeepJana You are in.

**Comment by Trodrige** [comment]
@teryhill I'm on this. I'll start separating PHP from HTML code. Then pull out more reusable code.

**Comment by teryhill** [comment]
This is done and the report generator is here. Closing this
