### ISSUE TITLE
feature request: calendar refresh on event panel exit

### ISSUE THREAD

**Issue by htuck** [LibreHealthIO/lh-ehr#824]
Possibly a GCI project; I didn't see it in earlier postings.
Can we have the calendar refresh when exiting the calendar event panel?
Seems simple enough to just do that on 'Save' button click.
As it is now, when you make any changes to the calendar you either have to wait the refresh interval or manually click on the tab's refresh icon to see the changes, and know the change was successful.  And  IMO that's one too many unnecessary clicks to remember to do.
- HT

![calendarrefresh](https://user-images.githubusercontent.com/8339489/33679093-9940b576-da72-11e7-912f-784e2cdd10b3.png)

and my acct still can't add labels, afaict

**Comment by teryhill** [comment]
Great Catch @htuck  I am sure one of the GCI's will jump on it. More tasks would be helpful Thanks

**Comment by htuck** [comment]
Thanks-- as the saying goes, "I got a MILLION of them!"
Actually, just a few... :)  and some of them may not be suitable for GCI but I'll post them and you can screen them.

**Comment by Jdew192837** [comment]
I can take this up. :)
