### ISSUE TITLE
Fees/Posting input errors

### ISSUE THREAD

**Issue by MigDinny** [LibreHealthIO/lh-ehr#871]
- In Fees/Posting >> submit all empty >> SQL Errors
- In Fees/Posting >> submit with any kind of data >> SQL Errors

**This kind of SQL errors:**

![image](https://user-images.githubusercontent.com/6632800/34180178-a9d00ffc-e505-11e7-80e6-0ef32897e015.png)

**Comment by teryhill** [comment]
Verify that it is happening on the demo site https://ehr.librehealth.io/interface/login/login.php?site=default.

If it is not happening on the demo site fix your copy.

**Comment by MigDinny** [comment]
@teryhill It is.

**Comment by teryhill** [comment]
Are you sure it is happening on the demo site?

**Comment by teryhill** [comment]
![image](https://user-images.githubusercontent.com/4655366/34180958-7d90b1a2-e4de-11e7-98d2-969eec296522.png)

**Comment by teryhill** [comment]
@MigDinny  I cannot replicate this issue on the demo site or on my local instance of the code.

**Comment by MigDinny** [comment]
@teryhill 
![image](https://user-images.githubusercontent.com/6632800/34186793-c172f366-e525-11e7-8864-140a7c8f9901.png)

Just get into the page and click on "PDF Download Selected Statements" with all fields empty.

**Comment by robbyoconnor** [comment]
This is worrying...

**Comment by teryhill** [comment]
@MigDinny you have not selected any data to process. Clerks are trained to select patients to process. I do not consider that an Issue @aethelwulffe or @tmccormi will need to approve this one. The label clearly states "Selected Statements"

**Comment by MigDinny** [comment]
@teryhill 

Yes, but this **should never happen in any circumstance** in a production environment.

You can't say that it's not a bug based on the fact that the user did the wrong thing. What I mean is that this must not happen (the SQL error) whatever the user does. I behaved like a casual user and this happened to me. If this can happen to me, it can happen to any other user. Concluding, this is a bug in my view.

**Comment by teryhill** [comment]
@MigDinny I consider it a training issue, My clients do not have that problem. If @aethelwulffe and @tmccormi say it is a bug then that is their decision. Me in my opinion it is not a bug it is misuse of the system. Like the 40 labels on a ladder because people misuse them.

**Comment by teryhill** [comment]
They are the owners of the repository and have ultimate say on what goes in.

**Comment by MigDinny** [comment]
@teryhill I understand. But for a program/software to be professional I think that this kind of stuff must be fixed and must be treated like any other bug. A misuse from the user must be prevented like we prevent bugs from happening.

**Comment by robbyoconnor** [comment]
@teryhill your opinion matters here -- feel empowered to state it's not a bug -- if it's a close call, you can ask for confirmation from @tmccormi and @aethelwulffe

**Comment by robbyoconnor** [comment]
Not a bug on the demo server.

**Comment by yehster** [comment]
It's a very low priority bug, since there is an easy workaround

It would be reasonable to determine if no checkboxes were selected and return an appropriate message instead of trying to proceeding with the invalid query.

This is where the error is happening...
https://github.com/LibreHealthIO/LibreEHR/blob/master/interface/billing/sl_eob_search.php#L241

**Comment by MigDinny** [comment]
@yehster Yes, that was I was talking about. Thanks for the information. Will work on that!

**Comment by yehster** [comment]
@MigDinny Professional software development is about understanding priorities.  It's not possible to fix everything.

**Comment by MigDinny** [comment]
@yehster It is, with time, but it is. And my experience on professional software taught me that this kind of stuff must not happen and because of that I'm putting my hands into work.

**Comment by yehster** [comment]
@MigDinny 
I showed you where a bug fix might go because I thought it could be a good learning experience for you.

However, your statements about your experience with professional software are a little bit insulting to the EHR team as you are basically suggesting that we are being unprofessional in our decision making

I'm happy for you that you found a way to address this issue, but the most important lesson you need to take away from this isn't about technical coding details.

**Comment by MigDinny** [comment]
@yehster that was completely unintentional. I'm sorry for that and I've already made a bugfix for that in a PR.

My intention was not to tell you (ehr team) were being unprofessional but to tell you that my personal experience as a costumer in many other services made my opinion. As a contributor my goal is not only coding features and fixing bugs and I think that contribution to the software's ergonomics and stuff like that is important as well. The intention was (and still is) good and seeks improvement.


Didn't want to offend anyone and I apologize for that @yehster. I just wanted to help as much as I could.

**Comment by aethelwulffe** [comment]
One thing about gaining new devs:  Things that are on a low priority list suddenly get to move up.

**Comment by MigDinny** [comment]
@aethelwulffe is that good or bad?

**Comment by aethelwulffe** [comment]
@MigDinny That's good Miguel.  It is very good.
Even if work is stalled on "big projects", or if there is no good overarching plan, fixing little things and cleaning shop is of greater value than some people realize.  It is also good for morale.  Morale === Happiness in your Sid Meyers Civilization game.
