### ISSUE TITLE
No Calendar in add/search patient.

### ISSUE THREAD

**Issue by phanindra789** [LibreHealthIO/lh-ehr#892]
In libreHealth EHR, go to:
Patient/Client --> Add New/Search -->Social Statistics --> Financial Review Date.
To enter date, calendar isn't opening.

**Comment by MigDinny** [comment]
This is a valid bug, in my opinion. Calendar popup should be opened when clicking on input.

@phanindra789 Will you fix this? If not, I can do it.

**Comment by phanindra789** [comment]
Guide me. I'll do it. Because, I too should learn!

**Comment by MigDinny** [comment]
@phanindra789 try to do it alone and if you need something, ask for help ;)

**Comment by phanindra789** [comment]
I asked you because, I know nothing how to do.
I know java and Android. So, if you give me some plan, Fill go in that way. :)

**Comment by MigDinny** [comment]
@phanindra789 well, it's not supposed for me to do your job. I can help you if needed, but I can't do it for you. Hint: inspect the codebase first and study how the code works.

**Comment by pri2si17-1997** [comment]
@phanindra789 This is not a bug but a kind of issue and shall be addressed. It is not affecting any functionality and user is able to enter date (though manually). Try jquery datepicker.

**Comment by aethelwulffe** [comment]
Actually, don't try datepicker.  use HTML5 date input type.
@phanindra789 this is still a good bug report.  @pri2si17-1997 it may not be broken code, but it is certainly the sort of thing that we are looking for, and an inconsistency == bug if not inconsistency === bug.
  The bigger question is "do we need the financial review field".  Aside from that, implementing date fields in the Layout engine this is related to make this a non-trivial thing.
