### ISSUE TITLE
New encounter not getting listed

### ISSUE THREAD

**Issue by sanjaykarthic** [LibreHealthIO/lh-ehr#896]
After creating a new encounter, its not listed in the encounter section.
can see a message that encounter already exists, but it is not seen in the list. Even if I select the issues and highlight the issue, nothing is getting listed on encounters.

![libre-new-encounter](https://user-images.githubusercontent.com/34680990/34375273-a66cd352-eb0b-11e7-8c64-2683f412b8b7.png)

**Comment by teryhill** [comment]
Tell me how you are getting to the screen?

**Comment by aethelwulffe** [comment]
These are the Issues linked to encounters review.  I vaguely recall this change.
