### ISSUE TITLE
sending message to All

### ISSUE THREAD

**Issue by sanjaykarthic** [LibreHealthIO/lh-ehr#897]
Message log says, Leave blank for all, but there is no option to leave blank, by default only 'Myself' is selected, no other way to leave a blank. so the functionality to send message to all cannot be achieved.
![librehealth-message-log](https://user-images.githubusercontent.com/34680990/34375370-38fa2292-eb0c-11e7-8b7d-4f25e6e2e49a.png)

**Comment by teryhill** [comment]
Need more information on how you got to this screen.

**Comment by teryhill** [comment]
closed on gitlab
