### ISSUE TITLE
GCI Task: Duplicate files in the code base.

### ISSUE THREAD

**Issue by phanindra789** [LibreHealthIO/lh-ehr#900]
**Sorry, if these aren't duplicate files. :)**  1.https://github.com/LibreHealthIO/LibreEHR/blob/master/interface/modules/zend_modules/public/css/CDA.xsl  
https://github.com/LibreHealthIO/LibreEHR/blob/master/interface/modules/zend_modules/public/xsl/ccd.xsl

2.https://github.com/LibreHealthIO/LibreEHR/blob/master/library/fonts/php_a010013l.afm
https://github.com/LibreHealthIO/LibreEHR/blob/master/library/fonts/php_a0100131.afm

3.https://github.com/LibreHealthIO/LibreEHR/blob/master/interface/modules/zend_modules/public/js/carecoordination/jquery.min.js
https://github.com/LibreHealthIO/LibreEHR/blob/master/assets/js/datatables/media/js/jquery.js

4.https://github.com/LibreHealthIO/LibreEHR/blob/master/assets/js/jquery-min-1-6-4/index.js
https://github.com/LibreHealthIO/LibreEHR/blob/master/library/js/jquery-1.6.4.min.js

5.https://github.com/LibreHealthIO/LibreEHR/blob/master/modules/calendar/full_calendar_scheduler/lib/fullcalendar.min.js
https://github.com/LibreHealthIO/LibreEHR/blob/master/modules/calendar/full_calendar/fullcalendar.min.js

@robbyoconnor Thanks in advance, if you consider these as duplicate files!

**Comment by robbyoconnor** [comment]
1 The first are not duplicates. Look at the spelling. -- **_INVALID_**
2. I'm not sure, but leaning towards **_INVALID_**
3. **Valid**
4. **Valid**
5. **Valid**

**Comment by aethelwulffe** [comment]
First two are no-go.
I think the second are the normal font and the italicized version.
The other three are total dupes.
  good catches. 

The main problem with these is that some are in modules, which are allowed their own versions of library assets.  That makes these worth consideration, but not immediate removal.  Still, you match the reporting criteria for this task.
You agree @robbyoconnor ?

**Comment by aethelwulffe** [comment]
@phanindra789 Sai, have you claimed this task?

**Comment by teryhill** [comment]
Agree 1 and 2 no everything else yes

**Comment by phanindra789** [comment]
@aethelwulffe Yes. I claimed this task.

**Comment by phanindra789** [comment]
@robbyoconnor 
https://github.com/LibreHealthIO/LibreEHR/tree/master/library/js/jquery.treeview-1.4.1/images
https://github.com/LibreHealthIO/LibreEHR/tree/master/interface/modules/zend_modules/public/css/jquery.treeview-1.4.1/images

**Comment by robbyoconnor** [comment]
I approved the task when I validated at least one or two. There is no real hard requirement on the number

**Comment by phanindra789** [comment]
@robbyoconnor   I didn't do it for the sake of task! I just want you to know that there are some more duplicate files.
and the above is a folder. Is that too a duplicate?

**Comment by pri2si17-1997** [comment]
@phanindra789 No doubt they are duplicate. But IMO second one was for zend module, and we are going to replace that. But this is good. :slightly_smiling_face: 

@teryhill @aethelwulffe can give you more insight on this.

**Comment by phanindra789** [comment]
@pri2si17-1997  Thank you.   
And the other thing is, I want someone with whom I can interact about other issues in EHR. are there anyone on chat now?

**Comment by aethelwulffe** [comment]
@phanindra789 @pri2si17-1997  we do have a sort of "rule" that you may duplicate files in a "module", but this module (and the whole interface/modules/zend_modules directory) needs to be completely dumped.
