### ISSUE TITLE
Warning when generating report - from patient screen

### ISSUE THREAD

**Issue by alpinus4** [LibreHealthIO/lh-ehr#961]
# Steps to reproduce: 
**1.** Enable displaying errors in _php.ini_

**2.** Go to patient screen and click _Report_

![](https://user-images.githubusercontent.com/25907897/35188011-4d7d96ba-fe2e-11e7-81ba-073f1d283ffe.jpg)

**3.** Click the second _Generate report_ button

![](https://user-images.githubusercontent.com/25907897/35188038-b5a582de-fe2e-11e7-9f09-0a6532a7784b.jpg)

**4.** See error

![](https://user-images.githubusercontent.com/25907897/35188041-c5168592-fe2e-11e7-8fbf-23f437154493.jpg)

Browser: Firefox 57.0.4
OS: Windows 10 ver. 1709

**Comment by teryhill** [comment]
Not getting the error on my system or the demo system, Do you have popups turned on?

**Comment by alpinus4** [comment]
Popups? I haven't enabled anything in _Administration_

**Comment by teryhill** [comment]
Enable popups in the browser

**Comment by alpinus4** [comment]
I have enabled popups on Chrome and Firefox. And on both throws error.

**Comment by teryhill** [comment]
Those are warnings. They are caused because the generatedXml directory is missing create it and the warnings will go away.

LibreEHR\ccr\generatedXml

**Comment by alpinus4** [comment]
Yea
