### ISSUE TITLE
Login and run a specific program

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/lh-ehr#971]
I would like to see the option to create a login "flowboard" and when that user is entered the Flow Board runs in full screen and only the flow board. This will need changes to the login screen to check for the flowboard login and perhaps changes to the flowboard to run in full screen.

**Comment by apooravc** [comment]
@teryhill I didn't get what you meant by a "flowboard". Would you please elaborate a bit?

**Comment by prabhakarpd7284** [comment]
Is it fine if it looks like this after login

![flow_board_full](https://user-images.githubusercontent.com/23030978/36340123-132787f8-13fc-11e8-952e-c8358b4b2899.png)

**Comment by apooravc** [comment]
This looks good. But what about the navigation bar? Where should that be put @teryhill ? Also, I think the "Status" drop down should be aligned properly, with this issue.

**Comment by prabhakarpd7284** [comment]
This preview looks better.

![flow_board_full_](https://user-images.githubusercontent.com/23030978/36341563-189a7136-1416-11e8-960c-47b5105f0ece.png)

**Comment by aethelwulffe** [comment]
I will check out that PR.  It looks like a useful option.

**Comment by aethelwulffe** [comment]
I like the PR.  I think that we need a toggle in globals to enable the feature, or maybe even a fine control in the user or user pref settings for "specific_application" or "single_application" or something.
  
The goal of such would be to allow a clinic to decide if they want this option on the login page, then allow the option to be a hard-set access control restriction on a user with or without the checkbox appearing on the login page.
