### ISSUE TITLE
Mousetip in Patient Search

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/lh-ehr#983]
Hover over the last name field in a Patient Finder row.  This field has an assigned background color, and shows a refresh icon that was intended to be a temp placeholder for something else as a replacement mouse tooltip.

-A very ugly and cheezy homemade-looking image...and not used in the right context.

**Comment by teryhill** [comment]
Didn't you create that image for one of the GCI guy's?

**Comment by aethelwulffe** [comment]
Yeah, then created a much better one...but it has snuck into some CSS, and it still exists.

**Comment by teryhill** [comment]
You got an envelope for the messages. @MigDinny added it to the code on the main screen but I think if a mail envelope showed up with a number it would be better.

**Comment by aethelwulffe** [comment]
I R Cornfuseded.  Knot nowe what enveloping and messages refers to.

**Comment by teryhill** [comment]
![image](https://user-images.githubusercontent.com/4655366/35711632-e7bc6290-078b-11e8-9fb1-27891ddd3798.png)

Picture fer u

**Comment by aethelwulffe** [comment]
Oh...it was a QUESTION. 
OK, image fer u.
![mail](https://user-images.githubusercontent.com/553751/35735078-5bdf4be6-07f1-11e8-9d69-bf34edf81af1.png)

**Comment by aethelwulffe** [comment]
It is padded to 64x64.  I can crop it or resize it larger or smaller depending on what you need for the scale.

**Comment by apooravc** [comment]
@aethelwulffe So we should remove the background color and the refresh icon when hovering over the last name? Or only the refresh icon?

**Comment by aethelwulffe** [comment]
@apooravc 
Sorry, I have been away for a few days.  My suggestion is to make things look right (consistent), function well, and help the user experience.  I think that the specifics should be left to you if you are doing the work.  My main advice to anyone working with the interface is to minimize the use of white-space.  Users need to see a lot of data, and our recent tendency (with bootstrap) has been to waste viewport space.

**Comment by apooravc** [comment]
@aethelwulffe Working on it.

**Comment by teryhill** [comment]
closed in gitlab
